import { errors } from '../../core/errors.js';
import { PERMISSIONS } from '../../core/permissions.js';
import { publicId, uuid } from '../../core/identifiers.js';
import { writeAudit } from '../../core/audit.js';
import { resolveStore } from '../catalog/service.js';

const storeHeader=(request)=>request.headers['x-store-id']||null;

export async function merchantInventoryRoutes(app){
  app.post('/v1/merchant/inventory/locations',{
    preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.INVENTORY_WRITE)],
    schema:{body:{type:'object',additionalProperties:false,required:['code','name'],properties:{code:{type:'string',minLength:1,maxLength:60,pattern:'^[A-Za-z0-9_-]+$'},name:{type:'string',minLength:1,maxLength:160},status:{type:'string',enum:['ACTIVE','INACTIVE'],default:'ACTIVE'},is_default:{type:'boolean',default:false}}}},
  },async(request,reply)=>{const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});
    const row=await app.db.transaction(async(client)=>{if(request.body.is_default) await client.query('UPDATE inventory_locations SET is_default=false,updated_at=now() WHERE tenant_id=$1 AND store_id=$2',[request.auth.tenantId,store.id]);
      const id=uuid();const publicID=publicId('loc');const result=await client.query(`INSERT INTO inventory_locations(id,public_id,tenant_id,store_id,code,name,status,is_default) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING public_id,code,name,status,is_default,created_at`,[id,publicID,request.auth.tenantId,store.id,request.body.code.trim().toUpperCase(),request.body.name.trim(),request.body.status||'ACTIVE',Boolean(request.body.is_default)]);
      await writeAudit(client,{tenantId:request.auth.tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'inventory.location.create',targetType:'inventory_location',targetId:id,metadata:{store_id:store.public_id,code:request.body.code.trim().toUpperCase()},requestIp:request.ip,requestId:request.id});return result.rows[0];});return reply.code(201).send({data:{location:row}});});

  app.get('/v1/merchant/inventory/locations',{preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.INVENTORY_READ)]},async(request)=>{const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});const result=await app.db.query('SELECT public_id,code,name,status,is_default,created_at,updated_at FROM inventory_locations WHERE tenant_id=$1 AND store_id=$2 ORDER BY is_default DESC,name',[request.auth.tenantId,store.id]);return {data:{store:{id:store.public_id,name:store.name},locations:result.rows}};});

  app.post('/v1/merchant/inventory/adjustments',{
    preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.INVENTORY_WRITE)],
    schema:{body:{type:'object',additionalProperties:false,required:['inventory_item_id','movement_type','quantity'],properties:{inventory_item_id:{type:'string',maxLength:100},location_id:{type:'string',maxLength:100},movement_type:{type:'string',enum:['RECEIVE','RETURN','ADJUSTMENT','DAMAGE']},quantity:{type:'integer',minimum:-999999999,maximum:999999999,not:{const:0}},reason:{type:'string',maxLength:1000},reference_type:{type:'string',maxLength:100},reference_id:{type:'string',maxLength:200}}}},
  },async(request,reply)=>{if(['RECEIVE','RETURN'].includes(request.body.movement_type)&&request.body.quantity<1) throw errors.badRequest('INVENTORY_QUANTITY_INVALID',`${request.body.movement_type} requires a positive quantity`);if(request.body.movement_type==='DAMAGE'&&request.body.quantity>-1) throw errors.badRequest('INVENTORY_QUANTITY_INVALID','DAMAGE requires a negative quantity');
    const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});
    const row=await app.db.transaction(async(client)=>{const item=await client.query(`SELECT i.id,i.public_id,i.product_id,i.variant_id,i.sku,i.track_inventory,p.public_id AS product_public_id,v.public_id AS variant_public_id FROM inventory_items i JOIN products p ON p.id=i.product_id AND p.tenant_id=i.tenant_id AND p.store_id=i.store_id LEFT JOIN product_variants v ON v.id=i.variant_id AND v.tenant_id=i.tenant_id AND v.store_id=i.store_id WHERE i.tenant_id=$1 AND i.store_id=$2 AND i.public_id=$3 AND i.status='ACTIVE' FOR UPDATE OF i`,[request.auth.tenantId,store.id,request.body.inventory_item_id]);if(!item.rowCount) throw errors.notFound('INVENTORY_ITEM_NOT_FOUND','Inventory item not found');if(!item.rows[0].track_inventory) throw errors.conflict('INVENTORY_TRACKING_DISABLED','Inventory tracking is disabled for this item');
      let location;if(request.body.location_id){location=await client.query("SELECT id,public_id FROM inventory_locations WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3 AND status='ACTIVE'",[request.auth.tenantId,store.id,request.body.location_id]);}else{location=await client.query("SELECT id,public_id FROM inventory_locations WHERE tenant_id=$1 AND store_id=$2 AND status='ACTIVE' ORDER BY is_default DESC,created_at LIMIT 1",[request.auth.tenantId,store.id]);}if(!location.rowCount) throw errors.notFound('INVENTORY_LOCATION_NOT_FOUND','Active inventory location not found');
      await client.query(`INSERT INTO inventory_balances(tenant_id,store_id,inventory_item_id,location_id,on_hand,reserved) VALUES($1,$2,$3,$4,0,0) ON CONFLICT DO NOTHING`,[request.auth.tenantId,store.id,item.rows[0].id,location.rows[0].id]);
      const balance=await client.query('SELECT on_hand,reserved FROM inventory_balances WHERE tenant_id=$1 AND store_id=$2 AND inventory_item_id=$3 AND location_id=$4 FOR UPDATE',[request.auth.tenantId,store.id,item.rows[0].id,location.rows[0].id]);const before=balance.rows[0];const nextOnHand=Number(before.on_hand)+request.body.quantity;const reserved=Number(before.reserved);if(nextOnHand<0) throw errors.conflict('INVENTORY_NEGATIVE_NOT_ALLOWED','Adjustment would make on-hand inventory negative');if(nextOnHand<reserved) throw errors.conflict('INVENTORY_RESERVED_CONFLICT','Adjustment would reduce on-hand inventory below reserved inventory');
      await client.query('UPDATE inventory_balances SET on_hand=$1,updated_at=now() WHERE tenant_id=$2 AND store_id=$3 AND inventory_item_id=$4 AND location_id=$5',[nextOnHand,request.auth.tenantId,store.id,item.rows[0].id,location.rows[0].id]);
      const ledger=await client.query(`INSERT INTO inventory_ledger(tenant_id,store_id,inventory_item_id,location_id,movement_type,on_hand_delta,reserved_delta,on_hand_after,reserved_after,reason,reference_type,reference_id,actor_type,actor_id,request_id) VALUES($1,$2,$3,$4,$5,$6,0,$7,$8,$9,$10,$11,'MERCHANT',$12,$13) RETURNING id,movement_type,on_hand_delta,reserved_delta,on_hand_after,reserved_after,reason,reference_type,reference_id,created_at`,[request.auth.tenantId,store.id,item.rows[0].id,location.rows[0].id,request.body.movement_type,request.body.quantity,nextOnHand,reserved,request.body.reason||null,request.body.reference_type||null,request.body.reference_id||null,request.auth.actorId,request.id]);
      await writeAudit(client,{tenantId:request.auth.tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'inventory.adjustment.create',targetType:'inventory_item',targetId:item.rows[0].id,metadata:{movement_type:request.body.movement_type,quantity:request.body.quantity,location_id:location.rows[0].public_id},requestIp:request.ip,requestId:request.id});return {...ledger.rows[0],inventory_item_id:item.rows[0].public_id,product_id:item.rows[0].product_public_id,variant_id:item.rows[0].variant_public_id,sku:item.rows[0].sku,location_id:location.rows[0].public_id};});return reply.code(201).send({data:{movement:row}});});

  app.get('/v1/merchant/inventory',{preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.INVENTORY_READ)]},async(request)=>{const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});const result=await app.db.query(`SELECT i.public_id AS inventory_item_id,p.public_id AS product_id,p.name AS product_name,v.public_id AS variant_id,v.title AS variant_title,i.sku,i.track_inventory,l.public_id AS location_id,l.name AS location_name,b.on_hand,b.reserved,(b.on_hand-b.reserved) AS available FROM inventory_items i JOIN products p ON p.id=i.product_id AND p.tenant_id=i.tenant_id AND p.store_id=i.store_id LEFT JOIN product_variants v ON v.id=i.variant_id AND v.tenant_id=i.tenant_id AND v.store_id=i.store_id LEFT JOIN inventory_balances b ON b.tenant_id=i.tenant_id AND b.store_id=i.store_id AND b.inventory_item_id=i.id LEFT JOIN inventory_locations l ON l.id=b.location_id AND l.tenant_id=b.tenant_id AND l.store_id=b.store_id WHERE i.tenant_id=$1 AND i.store_id=$2 AND i.status='ACTIVE' ORDER BY p.name,v.sort_order NULLS FIRST,l.name`,[request.auth.tenantId,store.id]);return {data:{store:{id:store.public_id,name:store.name},inventory:result.rows.map(r=>({...r,on_hand:r.on_hand===null?0:Number(r.on_hand),reserved:r.reserved===null?0:Number(r.reserved),available:r.available===null?0:Number(r.available)}))}};});

  app.get('/v1/merchant/inventory/ledger',{preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.INVENTORY_READ)],schema:{querystring:{type:'object',additionalProperties:false,properties:{inventory_item_id:{type:'string',maxLength:100},location_id:{type:'string',maxLength:100},limit:{type:'integer',minimum:1,maximum:200,default:100},offset:{type:'integer',minimum:0,maximum:1000000,default:0}}}}},async(request)=>{const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});const values=[request.auth.tenantId,store.id];let where='l.tenant_id=$1 AND l.store_id=$2';if(request.query.inventory_item_id){values.push(request.query.inventory_item_id);where+=` AND i.public_id=$${values.length}`;}if(request.query.location_id){values.push(request.query.location_id);where+=` AND loc.public_id=$${values.length}`;}values.push(request.query.limit||100,request.query.offset||0);const result=await app.db.query(`SELECT l.id,i.public_id AS inventory_item_id,p.public_id AS product_id,v.public_id AS variant_id,i.sku,loc.public_id AS location_id,loc.name AS location_name,l.movement_type,l.on_hand_delta,l.reserved_delta,l.on_hand_after,l.reserved_after,l.reason,l.reference_type,l.reference_id,l.actor_type,l.actor_id,l.request_id,l.created_at FROM inventory_ledger l JOIN inventory_items i ON i.id=l.inventory_item_id AND i.tenant_id=l.tenant_id AND i.store_id=l.store_id JOIN products p ON p.id=i.product_id AND p.tenant_id=i.tenant_id AND p.store_id=i.store_id LEFT JOIN product_variants v ON v.id=i.variant_id AND v.tenant_id=i.tenant_id AND v.store_id=i.store_id JOIN inventory_locations loc ON loc.id=l.location_id AND loc.tenant_id=l.tenant_id AND loc.store_id=l.store_id WHERE ${where} ORDER BY l.created_at DESC,l.id DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values);return {data:{ledger:result.rows.map(r=>({...r,on_hand_delta:Number(r.on_hand_delta),reserved_delta:Number(r.reserved_delta),on_hand_after:Number(r.on_hand_after),reserved_after:Number(r.reserved_after)})),limit:request.query.limit||100,offset:request.query.offset||0}};});
}
