import { errors } from '../../core/errors.js';
import { PERMISSIONS } from '../../core/permissions.js';
import { publicId, uuid } from '../../core/identifiers.js';
import { writeAudit } from '../../core/audit.js';
import { resolveStore } from '../catalog/service.js';
import { evaluateCustomerVip, getVipProgram, listVipBenefits, listVipLevels, normalizeBenefitConfig, validateVipLevel, vipMemberDetail, vipOverview } from './service.js';

const storeHeader=request=>request.headers['x-store-id']||null;
const readGuard=app=>[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.LOYALTY_READ)];
const manageGuard=app=>[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.LOYALTY_MANAGE)];
const programBody={type:'object',additionalProperties:false,minProperties:1,properties:{enabled:{type:'boolean'},evaluation_period:{type:'string',enum:['LIFETIME','ROLLING_30','ROLLING_90','ROLLING_180','ROLLING_365','CALENDAR_YEAR','CUSTOM']},custom_period_days:{type:['integer','null'],minimum:1,maximum:3650},evaluation_frequency:{type:'string',enum:['REALTIME','DAILY','WEEKLY','MONTHLY','MANUAL']},downgrade_policy:{type:'string',enum:['NEVER','REEVALUATE']},grace_days:{type:'integer',minimum:0,maximum:365}}};
const levelProps={name:{type:'string',minLength:1,maxLength:120},description:{type:['string','null'],maxLength:1000},badge_icon:{type:['string','null'],maxLength:80},badge_color:{type:['string','null'],maxLength:32},status:{type:'string',enum:['ACTIVE','INACTIVE']},sort_order:{type:'integer',minimum:-10000,maximum:10000},qualification_mode:{type:'string',enum:['SPEND','ORDERS','AND','OR']},spend_threshold:{type:['number','null'],minimum:0},order_threshold:{type:['integer','null'],minimum:0}};
const benefitProps={name:{type:'string',minLength:1,maxLength:160},benefit_type:{type:'string',enum:['FREE_DELIVERY','CASHBACK','VOUCHER','GIFT']},frequency:{type:'string',enum:['TIER_ENTRY','EVERY_ORDER','MONTHLY','ANNUAL','BIRTHDAY','MANUAL']},status:{type:'string',enum:['ACTIVE','INACTIVE']},config:{type:'object'},sort_order:{type:'integer',minimum:-10000,maximum:10000}};

async function storeFor(app,request){return resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});}
async function customerByRef(db,tenantId,ref){const r=await db.query(`SELECT id,public_id,customer_code,display_name FROM customers WHERE tenant_id=$1 AND (public_id=$2 OR customer_code=$2)`,[tenantId,ref]);if(!r.rowCount)throw errors.notFound('CUSTOMER_NOT_FOUND','Customer not found');return r.rows[0];}

export async function merchantLoyaltyRoutes(app){
 app.get('/v1/merchant/vip/program',{preHandler:readGuard(app)},async request=>{const store=await storeFor(app,request);return {data:{program:await getVipProgram(app.db,request.auth.tenantId,store.id),levels:await listVipLevels(app.db,request.auth.tenantId,store.id),benefits:await listVipBenefits(app.db,request.auth.tenantId,store.id)}};});

 app.put('/v1/merchant/vip/program',{preHandler:manageGuard(app),schema:{body:programBody}},async request=>{const store=await storeFor(app,request),tenantId=request.auth.tenantId,current=await getVipProgram(app.db,tenantId,store.id);if(!current)throw errors.notFound('VIP_PROGRAM_NOT_FOUND','VIP program not found');const b=request.body,period=b.evaluation_period??current.evaluation_period,custom=period==='CUSTOM'?(b.custom_period_days??current.custom_period_days):null;if(period==='CUSTOM'&&!custom)throw errors.badRequest('VIP_CUSTOM_PERIOD_REQUIRED','Custom evaluation period requires custom_period_days');await app.db.query(`UPDATE vip_programs SET enabled=$1,evaluation_period=$2,custom_period_days=$3,evaluation_frequency=$4,downgrade_policy=$5,grace_days=$6,updated_at=now() WHERE tenant_id=$7 AND store_id=$8`,[b.enabled??current.enabled,period,custom,b.evaluation_frequency??current.evaluation_frequency,b.downgrade_policy??current.downgrade_policy,b.grace_days??current.grace_days,tenantId,store.id]);await writeAudit(app.db,{tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'vip.program.update',targetType:'vip_program',targetId:current.internal_id,metadata:{enabled:b.enabled??current.enabled,evaluation_period:period,evaluation_frequency:b.evaluation_frequency??current.evaluation_frequency,downgrade_policy:b.downgrade_policy??current.downgrade_policy,grace_days:b.grace_days??current.grace_days},requestIp:request.ip,requestId:request.id});return {data:{program:await getVipProgram(app.db,tenantId,store.id)}};});

 app.get('/v1/merchant/vip/overview',{preHandler:readGuard(app)},async request=>{const store=await storeFor(app,request);return {data:await vipOverview(app.db,{tenantId:request.auth.tenantId,storeId:store.id})};});
 app.get('/v1/merchant/vip/levels',{preHandler:readGuard(app)},async request=>{const store=await storeFor(app,request);return {data:{levels:await listVipLevels(app.db,request.auth.tenantId,store.id)}};});

 app.post('/v1/merchant/vip/levels',{preHandler:manageGuard(app),schema:{body:{type:'object',additionalProperties:false,required:['code','name','qualification_mode'],properties:{code:{type:'string',minLength:1,maxLength:60},...levelProps}}}},async(request,reply)=>{const store=await storeFor(app,request),tenantId=request.auth.tenantId,program=await getVipProgram(app.db,tenantId,store.id);if(!program)throw errors.notFound('VIP_PROGRAM_NOT_FOUND','VIP program not found');const q=validateVipLevel(request.body),id=uuid(),pid=publicId('vipl');await app.db.query(`INSERT INTO vip_levels(id,public_id,tenant_id,store_id,program_id,code,name,description,badge_icon,badge_color,status,sort_order,qualification_mode,spend_threshold,order_threshold) VALUES($1,$2,$3,$4,$5,upper($6),$7,$8,$9,$10,$11,$12,$13,$14,$15)`,[id,pid,tenantId,store.id,program.internal_id,request.body.code.trim(),request.body.name.trim(),request.body.description?.trim()||null,request.body.badge_icon?.trim()||null,request.body.badge_color?.trim()||null,request.body.status||'ACTIVE',request.body.sort_order||0,q.qualification_mode,q.spend_threshold,q.order_threshold]);await writeAudit(app.db,{tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'vip.level.create',targetType:'vip_level',targetId:id,metadata:{code:request.body.code.trim().toUpperCase(),name:request.body.name.trim()},requestIp:request.ip,requestId:request.id});const level=(await listVipLevels(app.db,tenantId,store.id)).find(x=>x.id===pid);return reply.code(201).send({data:{level}});});

 app.patch('/v1/merchant/vip/levels/:levelId',{preHandler:manageGuard(app),schema:{body:{type:'object',additionalProperties:false,minProperties:1,properties:levelProps}}},async request=>{const store=await storeFor(app,request),tenantId=request.auth.tenantId,r=await app.db.query(`SELECT * FROM vip_levels WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3`,[tenantId,store.id,request.params.levelId]);if(!r.rowCount)throw errors.notFound('VIP_LEVEL_NOT_FOUND','VIP level not found');const c=r.rows[0],b=request.body,q=validateVipLevel(b,c);await app.db.query(`UPDATE vip_levels SET name=$1,description=$2,badge_icon=$3,badge_color=$4,status=$5,sort_order=$6,qualification_mode=$7,spend_threshold=$8,order_threshold=$9,updated_at=now() WHERE id=$10`,[b.name?.trim()??c.name,b.description!==undefined?(b.description?.trim()||null):c.description,b.badge_icon!==undefined?(b.badge_icon?.trim()||null):c.badge_icon,b.badge_color!==undefined?(b.badge_color?.trim()||null):c.badge_color,b.status??c.status,b.sort_order??c.sort_order,q.qualification_mode,q.spend_threshold,q.order_threshold,c.id]);await writeAudit(app.db,{tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'vip.level.update',targetType:'vip_level',targetId:c.id,metadata:{code:c.code},requestIp:request.ip,requestId:request.id});return {data:{level:(await listVipLevels(app.db,tenantId,store.id)).find(x=>x.id===request.params.levelId)}};});

 app.get('/v1/merchant/vip/benefits',{preHandler:readGuard(app)},async request=>{const store=await storeFor(app,request);return {data:{benefits:await listVipBenefits(app.db,request.auth.tenantId,store.id,{levelId:request.query?.level_id||null})}};});

 app.post('/v1/merchant/vip/benefits',{preHandler:manageGuard(app),schema:{body:{type:'object',additionalProperties:false,required:['level_id','name','benefit_type','frequency','config'],properties:{level_id:{type:'string',minLength:1,maxLength:120},...benefitProps}}}},async(request,reply)=>{const store=await storeFor(app,request),tenantId=request.auth.tenantId,level=await app.db.query(`SELECT id FROM vip_levels WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3`,[tenantId,store.id,request.body.level_id]);if(!level.rowCount)throw errors.notFound('VIP_LEVEL_NOT_FOUND','VIP level not found');const config=normalizeBenefitConfig(request.body.benefit_type,request.body.config),id=uuid(),pid=publicId('vipb');await app.db.query(`INSERT INTO vip_benefits(id,public_id,tenant_id,store_id,level_id,name,benefit_type,frequency,status,config,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11)`,[id,pid,tenantId,store.id,level.rows[0].id,request.body.name.trim(),request.body.benefit_type,request.body.frequency,request.body.status||'ACTIVE',JSON.stringify(config),request.body.sort_order||0]);await writeAudit(app.db,{tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'vip.benefit.create',targetType:'vip_benefit',targetId:id,metadata:{benefit_type:request.body.benefit_type,level_id:request.body.level_id},requestIp:request.ip,requestId:request.id});return reply.code(201).send({data:{benefit:(await listVipBenefits(app.db,tenantId,store.id)).find(x=>x.id===pid)}});});

 app.patch('/v1/merchant/vip/benefits/:benefitId',{preHandler:manageGuard(app),schema:{body:{type:'object',additionalProperties:false,minProperties:1,properties:benefitProps}}},async request=>{const store=await storeFor(app,request),tenantId=request.auth.tenantId,r=await app.db.query(`SELECT * FROM vip_benefits WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3`,[tenantId,store.id,request.params.benefitId]);if(!r.rowCount)throw errors.notFound('VIP_BENEFIT_NOT_FOUND','VIP benefit not found');const c=r.rows[0],b=request.body,type=b.benefit_type??c.benefit_type,config=b.config!==undefined?normalizeBenefitConfig(type,b.config):c.config;await app.db.query(`UPDATE vip_benefits SET name=$1,benefit_type=$2,frequency=$3,status=$4,config=$5::jsonb,sort_order=$6,updated_at=now() WHERE id=$7`,[b.name?.trim()??c.name,type,b.frequency??c.frequency,b.status??c.status,JSON.stringify(config),b.sort_order??c.sort_order,c.id]);await writeAudit(app.db,{tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'vip.benefit.update',targetType:'vip_benefit',targetId:c.id,metadata:{benefit_type:type},requestIp:request.ip,requestId:request.id});return {data:{benefit:(await listVipBenefits(app.db,tenantId,store.id)).find(x=>x.id===request.params.benefitId)}};});

 app.get('/v1/merchant/vip/members',{preHandler:readGuard(app),schema:{querystring:{type:'object',additionalProperties:false,properties:{q:{type:'string',maxLength:160},level_id:{type:'string',maxLength:120},limit:{type:'integer',minimum:1,maximum:200},offset:{type:'integer',minimum:0}}}}},async request=>{const store=await storeFor(app,request),tenantId=request.auth.tenantId,q=String(request.query?.q||'').trim(),levelRef=request.query?.level_id||null,limit=request.query?.limit||100,offset=request.query?.offset||0,values=[tenantId,store.id];let where='WHERE cvs.tenant_id=$1 AND cvs.store_id=$2';if(levelRef){values.push(levelRef);where+=` AND l.public_id=$${values.length}`;}if(q){values.push(`%${q}%`);where+=` AND (c.display_name ILIKE $${values.length} OR c.email ILIKE $${values.length} OR c.customer_code ILIKE $${values.length} OR c.public_id ILIKE $${values.length})`; }values.push(limit,offset);const rows=await app.db.query(`SELECT c.public_id AS customer_id,c.customer_code,c.display_name,c.email,c.phone_e164,c.status AS customer_status,cvs.public_id AS membership_id,cvs.assignment_source,cvs.locked,cvs.qualified_spend,cvs.qualified_orders,cvs.tier_expires_at,cvs.grace_until,cvs.evaluated_at,l.public_id AS level_id,l.name AS level_name,l.code AS level_code,l.badge_color,l.sort_order FROM customer_vip_status cvs JOIN customers c ON c.id=cvs.customer_id AND c.tenant_id=cvs.tenant_id LEFT JOIN vip_levels l ON l.id=cvs.level_id AND l.tenant_id=cvs.tenant_id AND l.store_id=cvs.store_id ${where} ORDER BY COALESCE(l.sort_order,-1) DESC,cvs.qualified_spend DESC,c.display_name LIMIT $${values.length-1} OFFSET $${values.length}`,values);return {data:{members:rows.rows,limit,offset}};});

 app.get('/v1/merchant/vip/members/:customerId',{preHandler:readGuard(app)},async request=>{const store=await storeFor(app,request);return {data:await vipMemberDetail(app.db,{tenantId:request.auth.tenantId,storeId:store.id,customerRef:request.params.customerId})};});

 app.post('/v1/merchant/vip/members/:customerId/evaluate',{preHandler:manageGuard(app)},async request=>{const store=await storeFor(app,request),tenantId=request.auth.tenantId,c=await customerByRef(app.db,tenantId,request.params.customerId);const result=await app.db.transaction(client=>evaluateCustomerVip(client,{tenantId,storeId:store.id,customerId:c.id,actorType:'MERCHANT',actorId:request.auth.actorId,source:'EVALUATION',reason:'Merchant requested VIP evaluation'}));await writeAudit(app.db,{tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'vip.member.evaluate',targetType:'customer',targetId:c.id,metadata:{changed:result.changed||false},requestIp:request.ip,requestId:request.id});return {data:{member:await vipMemberDetail(app.db,{tenantId,storeId:store.id,customerRef:c.public_id})}};});

 app.post('/v1/merchant/vip/evaluate',{preHandler:manageGuard(app),schema:{body:{type:'object',additionalProperties:false,properties:{limit:{type:'integer',minimum:1,maximum:500}}}}},async request=>{const store=await storeFor(app,request),tenantId=request.auth.tenantId,limit=request.body?.limit||200,customers=await app.db.query(`SELECT c.id,c.public_id FROM customers c WHERE c.tenant_id=$1 AND (EXISTS(SELECT 1 FROM orders o WHERE o.tenant_id=c.tenant_id AND o.store_id=$2 AND o.customer_id=c.id) OR EXISTS(SELECT 1 FROM customer_vip_status cvs WHERE cvs.tenant_id=c.tenant_id AND cvs.store_id=$2 AND cvs.customer_id=c.id)) ORDER BY c.created_at,c.id LIMIT $3`,[tenantId,store.id,limit]);let changed=0;for(const c of customers.rows){const result=await app.db.transaction(client=>evaluateCustomerVip(client,{tenantId,storeId:store.id,customerId:c.id,actorType:'MERCHANT',actorId:request.auth.actorId,source:'EVALUATION',reason:'Bulk VIP evaluation'}));if(result.changed)changed++;}await writeAudit(app.db,{tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'vip.bulk_evaluate',targetType:'store',targetId:store.id,metadata:{evaluated:customers.rowCount,changed},requestIp:request.ip,requestId:request.id});return {data:{evaluated:customers.rowCount,changed}};});

 app.put('/v1/merchant/vip/members/:customerId/assignment',{preHandler:manageGuard(app),schema:{body:{type:'object',additionalProperties:false,required:['level_id','reason'],properties:{level_id:{type:['string','null'],maxLength:120},locked:{type:'boolean'},tier_expires_at:{type:['string','null'],format:'date-time'},reason:{type:'string',minLength:3,maxLength:1000}}}}},async request=>{const store=await storeFor(app,request),tenantId=request.auth.tenantId,c=await customerByRef(app.db,tenantId,request.params.customerId);await app.db.transaction(async client=>{const current=await client.query(`SELECT * FROM customer_vip_status WHERE tenant_id=$1 AND store_id=$2 AND customer_id=$3 FOR UPDATE`,[tenantId,store.id,c.id]);let level=null;if(request.body.level_id){const l=await client.query(`SELECT id,public_id,name FROM vip_levels WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3`,[tenantId,store.id,request.body.level_id]);if(!l.rowCount)throw errors.notFound('VIP_LEVEL_NOT_FOUND','VIP level not found');level=l.rows[0];}const old=current.rows[0]||null;if(old)await client.query(`UPDATE customer_vip_status SET level_id=$1,assignment_source='MANUAL',locked=$2,tier_expires_at=$3,grace_until=NULL,updated_at=now() WHERE id=$4`,[level?.id||null,request.body.locked??true,request.body.tier_expires_at??null,old.id]);else await client.query(`INSERT INTO customer_vip_status(id,public_id,tenant_id,store_id,customer_id,level_id,assignment_source,locked,tier_expires_at) VALUES($1,$2,$3,$4,$5,$6,'MANUAL',$7,$8)`,[uuid(),publicId('vipm'),tenantId,store.id,c.id,level?.id||null,request.body.locked??true,request.body.tier_expires_at??null]);if((old?.level_id||null)!==(level?.id||null))await client.query(`INSERT INTO vip_tier_history(tenant_id,store_id,customer_id,from_level_id,to_level_id,source,reason,actor_type,actor_id) VALUES($1,$2,$3,$4,$5,'MANUAL',$6,'MERCHANT',$7)`,[tenantId,store.id,c.id,old?.level_id||null,level?.id||null,request.body.reason,request.auth.actorId]);});await writeAudit(app.db,{tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'vip.member.assign',targetType:'customer',targetId:c.id,metadata:{level_id:request.body.level_id,locked:request.body.locked??true,tier_expires_at:request.body.tier_expires_at??null,reason:request.body.reason},requestIp:request.ip,requestId:request.id});return {data:await vipMemberDetail(app.db,{tenantId,storeId:store.id,customerRef:c.public_id})};});
}
