import { errors } from '../../core/errors.js';
import { PERMISSIONS } from '../../core/permissions.js';
import { publicId, uuid } from '../../core/identifiers.js';
import { writeAudit } from '../../core/audit.js';
import { resolveStore } from '../catalog/service.js';

const storeHeader=request=>request.headers['x-store-id']||null;
const readGuard=app=>[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.DELIVERY_READ)];
const manageGuard=app=>[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.DELIVERY_MANAGE)];
const physicalDispatchTypes=new Set(['PHYSICAL_SHIPPING','PHYSICAL_LOCAL_DELIVERY','FOOD_DELIVERY']);
const terminalFulfillment=new Set(['DELIVERED','COMPLETED','FAILED','CANCELLED']);
const terminalDispatch=new Set(['DELIVERED','CANCELLED']);

async function merchantStore(app,request){return resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});}
const zoneSelect=`SELECT z.public_id AS id,z.code,z.name,z.status,z.match_type,z.country_codes,z.region_names,z.center_latitude,z.center_longitude,z.radius_km,z.sort_order,z.metadata,z.created_at,z.updated_at FROM delivery_zones z`;
const rateSelect=`SELECT r.public_id AS id,z.public_id AS zone_id,z.code AS zone_code,dm.public_id AS delivery_method_id,dm.code AS delivery_method_code,dm.name AS delivery_method_name,dm.fulfillment_mode,r.status,r.flat_fee,r.free_over,r.min_order,r.estimated_min_minutes,r.estimated_max_minutes,r.priority,r.metadata,r.created_at,r.updated_at FROM delivery_zone_rates r JOIN delivery_zones z ON z.id=r.zone_id AND z.tenant_id=r.tenant_id AND z.store_id=r.store_id JOIN delivery_methods dm ON dm.id=r.delivery_method_id AND dm.tenant_id=r.tenant_id AND dm.store_id=r.store_id`;
const driverSelect=`SELECT d.public_id AS id,d.display_name,d.phone_e164,d.status,d.vehicle_type,d.vehicle_label,d.metadata,d.created_at,d.updated_at,mu.public_id AS merchant_user_id,mu.email AS merchant_user_email FROM delivery_drivers d LEFT JOIN merchant_users mu ON mu.id=d.merchant_user_id AND mu.tenant_id=d.tenant_id`;
const dispatchSelect=`SELECT x.public_id AS id,x.status,x.assigned_at,x.accepted_at,x.picked_up_at,x.out_for_delivery_at,x.delivered_at,x.cancelled_at,x.cancellation_reason,x.notes,x.created_at,x.updated_at,d.public_id AS driver_id,d.display_name AS driver_name,d.phone_e164 AS driver_phone,d.vehicle_type,d.vehicle_label,f.public_id AS fulfillment_id,f.fulfillment_type,f.fulfillment_mode,f.status AS fulfillment_status,o.public_id AS order_id,o.order_number FROM delivery_dispatches x JOIN delivery_drivers d ON d.id=x.driver_id AND d.tenant_id=x.tenant_id AND d.store_id=x.store_id JOIN order_fulfillments f ON f.id=x.fulfillment_id AND f.tenant_id=x.tenant_id AND f.store_id=x.store_id JOIN orders o ON o.id=f.order_id AND o.tenant_id=f.tenant_id AND o.store_id=f.store_id`;

function normalizeZoneBody(body,current={}){
 const matchType=body.match_type??current.match_type;
 const countryCodes=body.country_codes!==undefined?[...new Set(body.country_codes.map(v=>String(v).trim().toUpperCase()).filter(Boolean))]:(current.country_codes||[]);
 const regionNames=body.region_names!==undefined?[...new Set(body.region_names.map(v=>String(v).trim()).filter(Boolean))]:(current.region_names||[]);
 const centerLatitude=body.center_latitude!==undefined?body.center_latitude:current.center_latitude;
 const centerLongitude=body.center_longitude!==undefined?body.center_longitude:current.center_longitude;
 const radiusKm=body.radius_km!==undefined?body.radius_km:current.radius_km;
 if(matchType==='COUNTRY_REGION'&&!countryCodes.length)throw errors.badRequest('DELIVERY_ZONE_COUNTRY_REQUIRED','Country/region zones require at least one country code');
 if(matchType==='RADIUS'&&(centerLatitude==null||centerLongitude==null||radiusKm==null))throw errors.badRequest('DELIVERY_ZONE_RADIUS_REQUIRED','Radius zones require center latitude, longitude, and radius');
 return {matchType,countryCodes:matchType==='COUNTRY_REGION'?countryCodes:[],regionNames:matchType==='COUNTRY_REGION'?regionNames:[],centerLatitude:matchType==='RADIUS'?Number(centerLatitude):null,centerLongitude:matchType==='RADIUS'?Number(centerLongitude):null,radiusKm:matchType==='RADIUS'?Number(radiusKm):null};
}

async function zoneByRef(db,tenantId,storeId,ref){const row=await db.query(`SELECT * FROM delivery_zones WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3`,[tenantId,storeId,ref]);if(!row.rowCount)throw errors.notFound('DELIVERY_ZONE_NOT_FOUND','Delivery zone not found');return row.rows[0];}
async function rateByRef(db,tenantId,storeId,ref){const row=await db.query(`SELECT * FROM delivery_zone_rates WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3`,[tenantId,storeId,ref]);if(!row.rowCount)throw errors.notFound('DELIVERY_ZONE_RATE_NOT_FOUND','Delivery zone rate not found');return row.rows[0];}
async function driverByRef(db,tenantId,storeId,ref,{active=false}={}){const row=await db.query(`SELECT * FROM delivery_drivers WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3${active?" AND status='ACTIVE'":''}`,[tenantId,storeId,ref]);if(!row.rowCount)throw errors.notFound('DELIVERY_DRIVER_NOT_FOUND',active?'Active driver not found':'Driver not found');return row.rows[0];}
async function dispatchByRef(db,tenantId,storeId,ref,{lock=false}={}){const row=await db.query(`SELECT * FROM delivery_dispatches WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3${lock?' FOR UPDATE':''}`,[tenantId,storeId,ref]);if(!row.rowCount)throw errors.notFound('DELIVERY_DISPATCH_NOT_FOUND','Dispatch assignment not found');return row.rows[0];}

export async function deliveryOperationsRoutes(app){
 app.get('/v1/merchant/delivery/zones',{preHandler:readGuard(app)},async request=>{
  const store=await merchantStore(app,request);const [zones,rates]=await Promise.all([
   app.db.query(`${zoneSelect} WHERE z.tenant_id=$1 AND z.store_id=$2 ORDER BY z.sort_order,z.created_at,z.id`,[request.auth.tenantId,store.id]),
   app.db.query(`${rateSelect} WHERE r.tenant_id=$1 AND r.store_id=$2 ORDER BY z.sort_order,r.priority,r.created_at,r.id`,[request.auth.tenantId,store.id]),
  ]);return {data:{zones:zones.rows,rates:rates.rows,checkout_pricing_mode:'DELIVERY_METHOD_BASELINE'}};
 });

 app.post('/v1/merchant/delivery/zones',{preHandler:manageGuard(app),schema:{body:{type:'object',additionalProperties:false,required:['code','name','match_type'],properties:{code:{type:'string',minLength:1,maxLength:60},name:{type:'string',minLength:1,maxLength:120},status:{type:'string',enum:['ACTIVE','INACTIVE']},match_type:{type:'string',enum:['COUNTRY_REGION','RADIUS']},country_codes:{type:'array',maxItems:50,items:{type:'string',minLength:2,maxLength:2}},region_names:{type:'array',maxItems:100,items:{type:'string',minLength:1,maxLength:120}},center_latitude:{type:['number','null'],minimum:-90,maximum:90},center_longitude:{type:['number','null'],minimum:-180,maximum:180},radius_km:{type:['number','null'],exclusiveMinimum:0,maximum:50000},sort_order:{type:'integer',minimum:-10000,maximum:10000},metadata:{type:'object'}}}}},async(request,reply)=>{
  const store=await merchantStore(app,request),zone=normalizeZoneBody(request.body);const id=uuid(),pid=publicId('dzn');
  await app.db.transaction(async client=>{await client.query(`INSERT INTO delivery_zones(id,public_id,tenant_id,store_id,code,name,status,match_type,country_codes,region_names,center_latitude,center_longitude,radius_km,sort_order,metadata) VALUES($1,$2,$3,$4,upper($5),$6,$7,$8,$9,$10,$11,$12,$13,$14,$15::jsonb)`,[id,pid,request.auth.tenantId,store.id,request.body.code.trim(),request.body.name.trim(),request.body.status||'ACTIVE',zone.matchType,zone.countryCodes,zone.regionNames,zone.centerLatitude,zone.centerLongitude,zone.radiusKm,request.body.sort_order||0,JSON.stringify(request.body.metadata||{})]);await writeAudit(client,{tenantId:request.auth.tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'delivery.zone.create',targetType:'delivery_zone',targetId:id,metadata:{code:request.body.code.trim().toUpperCase(),match_type:zone.matchType},requestIp:request.ip,requestId:request.id});});
  const created=await app.db.query(`${zoneSelect} WHERE z.id=$1`,[id]);return reply.code(201).send({data:{zone:created.rows[0]}});
 });

 app.patch('/v1/merchant/delivery/zones/:zoneId',{preHandler:manageGuard(app),schema:{body:{type:'object',additionalProperties:false,minProperties:1,properties:{name:{type:'string',minLength:1,maxLength:120},status:{type:'string',enum:['ACTIVE','INACTIVE']},match_type:{type:'string',enum:['COUNTRY_REGION','RADIUS']},country_codes:{type:'array',maxItems:50,items:{type:'string',minLength:2,maxLength:2}},region_names:{type:'array',maxItems:100,items:{type:'string',minLength:1,maxLength:120}},center_latitude:{type:['number','null'],minimum:-90,maximum:90},center_longitude:{type:['number','null'],minimum:-180,maximum:180},radius_km:{type:['number','null'],exclusiveMinimum:0,maximum:50000},sort_order:{type:'integer',minimum:-10000,maximum:10000},metadata:{type:'object'}}}}},async request=>{
  const store=await merchantStore(app,request),current=await zoneByRef(app.db,request.auth.tenantId,store.id,request.params.zoneId),zone=normalizeZoneBody(request.body,current);
  await app.db.transaction(async client=>{await client.query(`UPDATE delivery_zones SET name=$1,status=$2,match_type=$3,country_codes=$4,region_names=$5,center_latitude=$6,center_longitude=$7,radius_km=$8,sort_order=$9,metadata=$10::jsonb,updated_at=now() WHERE id=$11`,[request.body.name?.trim()??current.name,request.body.status??current.status,zone.matchType,zone.countryCodes,zone.regionNames,zone.centerLatitude,zone.centerLongitude,zone.radiusKm,request.body.sort_order??current.sort_order,JSON.stringify(request.body.metadata??current.metadata??{}),current.id]);await writeAudit(client,{tenantId:request.auth.tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'delivery.zone.update',targetType:'delivery_zone',targetId:current.id,metadata:{status:request.body.status??current.status,match_type:zone.matchType},requestIp:request.ip,requestId:request.id});});
  return {data:{zone:(await app.db.query(`${zoneSelect} WHERE z.id=$1`,[current.id])).rows[0]}};
 });

 app.post('/v1/merchant/delivery/zones/:zoneId/rates',{preHandler:manageGuard(app),schema:{body:{type:'object',additionalProperties:false,required:['delivery_method_id','flat_fee'],properties:{delivery_method_id:{type:'string',minLength:1,maxLength:100},status:{type:'string',enum:['ACTIVE','INACTIVE']},flat_fee:{type:'number',minimum:0},free_over:{type:['number','null'],minimum:0},min_order:{type:'number',minimum:0},estimated_min_minutes:{type:['integer','null'],minimum:0},estimated_max_minutes:{type:['integer','null'],minimum:0},priority:{type:'integer',minimum:-10000,maximum:10000},metadata:{type:'object'}}}}},async(request,reply)=>{
  const store=await merchantStore(app,request),zone=await zoneByRef(app.db,request.auth.tenantId,store.id,request.params.zoneId);const method=await app.db.query(`SELECT * FROM delivery_methods WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3 AND fulfillment_mode IN ('SHIPPING','LOCAL_DELIVERY')`,[request.auth.tenantId,store.id,request.body.delivery_method_id]);if(!method.rowCount)throw errors.notFound('DELIVERY_METHOD_NOT_FOUND','Shipping or local-delivery method not found');if(request.body.estimated_min_minutes!=null&&request.body.estimated_max_minutes!=null&&request.body.estimated_max_minutes<request.body.estimated_min_minutes)throw errors.badRequest('DELIVERY_ZONE_RATE_ETA_INVALID','Maximum estimate must be greater than or equal to minimum estimate');const id=uuid(),pid=publicId('dzr');
  await app.db.transaction(async client=>{await client.query(`INSERT INTO delivery_zone_rates(id,public_id,tenant_id,store_id,zone_id,delivery_method_id,status,flat_fee,free_over,min_order,estimated_min_minutes,estimated_max_minutes,priority,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb)`,[id,pid,request.auth.tenantId,store.id,zone.id,method.rows[0].id,request.body.status||'ACTIVE',request.body.flat_fee,request.body.free_over??null,request.body.min_order||0,request.body.estimated_min_minutes??null,request.body.estimated_max_minutes??null,request.body.priority||0,JSON.stringify(request.body.metadata||{})]);await writeAudit(client,{tenantId:request.auth.tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'delivery.zone_rate.create',targetType:'delivery_zone_rate',targetId:id,metadata:{zone_id:zone.public_id,delivery_method_id:method.rows[0].public_id,checkout_applied:false},requestIp:request.ip,requestId:request.id});});return reply.code(201).send({data:{rate:(await app.db.query(`${rateSelect} WHERE r.id=$1`,[id])).rows[0],checkout_applied:false}});
 });

 app.patch('/v1/merchant/delivery/zone-rates/:rateId',{preHandler:manageGuard(app),schema:{body:{type:'object',additionalProperties:false,minProperties:1,properties:{status:{type:'string',enum:['ACTIVE','INACTIVE']},flat_fee:{type:'number',minimum:0},free_over:{type:['number','null'],minimum:0},min_order:{type:'number',minimum:0},estimated_min_minutes:{type:['integer','null'],minimum:0},estimated_max_minutes:{type:['integer','null'],minimum:0},priority:{type:'integer',minimum:-10000,maximum:10000},metadata:{type:'object'}}}}},async request=>{
  const store=await merchantStore(app,request),current=await rateByRef(app.db,request.auth.tenantId,store.id,request.params.rateId);const min=request.body.estimated_min_minutes!==undefined?request.body.estimated_min_minutes:current.estimated_min_minutes,max=request.body.estimated_max_minutes!==undefined?request.body.estimated_max_minutes:current.estimated_max_minutes;if(min!=null&&max!=null&&max<min)throw errors.badRequest('DELIVERY_ZONE_RATE_ETA_INVALID','Maximum estimate must be greater than or equal to minimum estimate');
  await app.db.transaction(async client=>{await client.query(`UPDATE delivery_zone_rates SET status=$1,flat_fee=$2,free_over=$3,min_order=$4,estimated_min_minutes=$5,estimated_max_minutes=$6,priority=$7,metadata=$8::jsonb,updated_at=now() WHERE id=$9`,[request.body.status??current.status,request.body.flat_fee??current.flat_fee,request.body.free_over!==undefined?request.body.free_over:current.free_over,request.body.min_order??current.min_order,min,max,request.body.priority??current.priority,JSON.stringify(request.body.metadata??current.metadata??{}),current.id]);await writeAudit(client,{tenantId:request.auth.tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'delivery.zone_rate.update',targetType:'delivery_zone_rate',targetId:current.id,metadata:{checkout_applied:false},requestIp:request.ip,requestId:request.id});});return {data:{rate:(await app.db.query(`${rateSelect} WHERE r.id=$1`,[current.id])).rows[0],checkout_applied:false}};
 });

 app.get('/v1/merchant/delivery/drivers',{preHandler:readGuard(app)},async request=>{const store=await merchantStore(app,request);const rows=await app.db.query(`${driverSelect} WHERE d.tenant_id=$1 AND d.store_id=$2 ORDER BY CASE d.status WHEN 'ACTIVE' THEN 0 WHEN 'INACTIVE' THEN 1 ELSE 2 END,d.display_name,d.created_at`,[request.auth.tenantId,store.id]);return {data:{drivers:rows.rows}};});

 app.post('/v1/merchant/delivery/drivers',{preHandler:manageGuard(app),schema:{body:{type:'object',additionalProperties:false,required:['display_name'],properties:{display_name:{type:'string',minLength:1,maxLength:120},phone_e164:{type:['string','null'],maxLength:32},status:{type:'string',enum:['ACTIVE','INACTIVE','SUSPENDED']},vehicle_type:{type:['string','null'],enum:['BIKE','MOTORBIKE','CAR','VAN','TRUCK','OTHER',null]},vehicle_label:{type:['string','null'],maxLength:120},merchant_user_id:{type:['string','null'],maxLength:100},metadata:{type:'object'}}}}},async(request,reply)=>{
  const store=await merchantStore(app,request);let merchantUserId=null;if(request.body.merchant_user_id){const user=await app.db.query(`SELECT id FROM merchant_users WHERE tenant_id=$1 AND public_id=$2`,[request.auth.tenantId,request.body.merchant_user_id]);if(!user.rowCount)throw errors.notFound('MERCHANT_USER_NOT_FOUND','Merchant user not found');merchantUserId=user.rows[0].id;}const id=uuid(),pid=publicId('drv');
  await app.db.transaction(async client=>{await client.query(`INSERT INTO delivery_drivers(id,public_id,tenant_id,store_id,merchant_user_id,display_name,phone_e164,status,vehicle_type,vehicle_label,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb)`,[id,pid,request.auth.tenantId,store.id,merchantUserId,request.body.display_name.trim(),request.body.phone_e164?.trim()||null,request.body.status||'ACTIVE',request.body.vehicle_type??null,request.body.vehicle_label?.trim()||null,JSON.stringify(request.body.metadata||{})]);await writeAudit(client,{tenantId:request.auth.tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'delivery.driver.create',targetType:'delivery_driver',targetId:id,metadata:{display_name:request.body.display_name.trim(),merchant_user_id:request.body.merchant_user_id||null},requestIp:request.ip,requestId:request.id});});return reply.code(201).send({data:{driver:(await app.db.query(`${driverSelect} WHERE d.id=$1`,[id])).rows[0]}});
 });

 app.patch('/v1/merchant/delivery/drivers/:driverId',{preHandler:manageGuard(app),schema:{body:{type:'object',additionalProperties:false,minProperties:1,properties:{display_name:{type:'string',minLength:1,maxLength:120},phone_e164:{type:['string','null'],maxLength:32},status:{type:'string',enum:['ACTIVE','INACTIVE','SUSPENDED']},vehicle_type:{type:['string','null'],enum:['BIKE','MOTORBIKE','CAR','VAN','TRUCK','OTHER',null]},vehicle_label:{type:['string','null'],maxLength:120},merchant_user_id:{type:['string','null'],maxLength:100},metadata:{type:'object'}}}}},async request=>{
  const store=await merchantStore(app,request),current=await driverByRef(app.db,request.auth.tenantId,store.id,request.params.driverId);let merchantUserId=current.merchant_user_id;if(request.body.merchant_user_id!==undefined){if(request.body.merchant_user_id===null)merchantUserId=null;else{const user=await app.db.query(`SELECT id FROM merchant_users WHERE tenant_id=$1 AND public_id=$2`,[request.auth.tenantId,request.body.merchant_user_id]);if(!user.rowCount)throw errors.notFound('MERCHANT_USER_NOT_FOUND','Merchant user not found');merchantUserId=user.rows[0].id;}}
  await app.db.transaction(async client=>{await client.query(`UPDATE delivery_drivers SET merchant_user_id=$1,display_name=$2,phone_e164=$3,status=$4,vehicle_type=$5,vehicle_label=$6,metadata=$7::jsonb,updated_at=now() WHERE id=$8`,[merchantUserId,request.body.display_name?.trim()??current.display_name,request.body.phone_e164!==undefined?(request.body.phone_e164?.trim()||null):current.phone_e164,request.body.status??current.status,request.body.vehicle_type!==undefined?request.body.vehicle_type:current.vehicle_type,request.body.vehicle_label!==undefined?(request.body.vehicle_label?.trim()||null):current.vehicle_label,JSON.stringify(request.body.metadata??current.metadata??{}),current.id]);await writeAudit(client,{tenantId:request.auth.tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'delivery.driver.update',targetType:'delivery_driver',targetId:current.id,metadata:{status:request.body.status??current.status,merchant_user_id:request.body.merchant_user_id??null},requestIp:request.ip,requestId:request.id});});return {data:{driver:(await app.db.query(`${driverSelect} WHERE d.id=$1`,[current.id])).rows[0]}};
 });

 app.get('/v1/merchant/delivery/dispatches',{preHandler:readGuard(app),schema:{querystring:{type:'object',additionalProperties:false,properties:{status:{type:'string',enum:['ASSIGNED','ACCEPTED','PICKED_UP','OUT_FOR_DELIVERY','DELIVERED','CANCELLED']},driver_id:{type:'string',maxLength:100},limit:{type:'integer',minimum:1,maximum:200}}}}},async request=>{
  const store=await merchantStore(app,request),params=[request.auth.tenantId,store.id];let filter='x.tenant_id=$1 AND x.store_id=$2';if(request.query.status){params.push(request.query.status);filter+=` AND x.status=$${params.length}`;}if(request.query.driver_id){params.push(request.query.driver_id);filter+=` AND d.public_id=$${params.length}`;}params.push(request.query.limit||100);const rows=await app.db.query(`${dispatchSelect} WHERE ${filter} ORDER BY CASE WHEN x.status IN ('DELIVERED','CANCELLED') THEN 1 ELSE 0 END,x.assigned_at DESC,x.id DESC LIMIT $${params.length}`,params);return {data:{dispatches:rows.rows}};
 });

 app.get('/v1/merchant/delivery/dispatches/:dispatchId',{preHandler:readGuard(app)},async request=>{
  const store=await merchantStore(app,request),row=await app.db.query(`${dispatchSelect} WHERE x.tenant_id=$1 AND x.store_id=$2 AND x.public_id=$3`,[request.auth.tenantId,store.id,request.params.dispatchId]);if(!row.rowCount)throw errors.notFound('DELIVERY_DISPATCH_NOT_FOUND','Dispatch assignment not found');const events=await app.db.query(`SELECT event_type,actor_type,from_status,to_status,reason,metadata,created_at FROM delivery_dispatch_events e JOIN delivery_dispatches x ON x.id=e.dispatch_id AND x.tenant_id=e.tenant_id AND x.store_id=e.store_id WHERE e.tenant_id=$1 AND e.store_id=$2 AND x.public_id=$3 ORDER BY e.created_at,e.id`,[request.auth.tenantId,store.id,request.params.dispatchId]);return {data:{dispatch:{...row.rows[0],events:events.rows}}};
 });

 app.post('/v1/merchant/delivery/dispatches',{preHandler:manageGuard(app),schema:{body:{type:'object',additionalProperties:false,required:['fulfillment_id','driver_id'],properties:{fulfillment_id:{type:'string',minLength:1,maxLength:100},driver_id:{type:'string',minLength:1,maxLength:100},notes:{type:['string','null'],maxLength:2000}}}}},async(request,reply)=>{
  const store=await merchantStore(app,request),driver=await driverByRef(app.db,request.auth.tenantId,store.id,request.body.driver_id,{active:true});const fulfillment=await app.db.query(`SELECT f.*,o.order_number FROM order_fulfillments f JOIN orders o ON o.id=f.order_id AND o.tenant_id=f.tenant_id AND o.store_id=f.store_id WHERE f.tenant_id=$1 AND f.store_id=$2 AND f.public_id=$3`,[request.auth.tenantId,store.id,request.body.fulfillment_id]);if(!fulfillment.rowCount)throw errors.notFound('FULFILLMENT_NOT_FOUND','Fulfillment not found');const f=fulfillment.rows[0];if(!physicalDispatchTypes.has(f.fulfillment_type))throw errors.conflict('DELIVERY_DISPATCH_TYPE_UNSUPPORTED','Only shipping and delivery fulfillments can be dispatched to drivers');if(terminalFulfillment.has(f.status))throw errors.conflict('DELIVERY_DISPATCH_FULFILLMENT_TERMINAL','Terminal fulfillments cannot be dispatched');const id=uuid(),pid=publicId('dsp');
  await app.db.transaction(async client=>{await client.query(`INSERT INTO delivery_dispatches(id,public_id,tenant_id,store_id,fulfillment_id,driver_id,status,assigned_by,notes) VALUES($1,$2,$3,$4,$5,$6,'ASSIGNED',$7,$8)`,[id,pid,request.auth.tenantId,store.id,f.id,driver.id,request.auth.actorId,request.body.notes?.trim()||null]);await client.query(`INSERT INTO delivery_dispatch_events(tenant_id,store_id,dispatch_id,event_type,actor_type,actor_id,to_driver_id,to_status,reason,request_id) VALUES($1,$2,$3,'ASSIGNED','MERCHANT',$4,$5,'ASSIGNED',$6,$7)`,[request.auth.tenantId,store.id,id,request.auth.actorId,driver.id,request.body.notes?.trim()||null,request.id]);await writeAudit(client,{tenantId:request.auth.tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'delivery.dispatch.assign',targetType:'delivery_dispatch',targetId:id,metadata:{fulfillment_id:f.public_id,driver_id:driver.public_id,order_number:f.order_number},requestIp:request.ip,requestId:request.id});});return reply.code(201).send({data:{dispatch:(await app.db.query(`${dispatchSelect} WHERE x.id=$1`,[id])).rows[0]}});
 });

 app.patch('/v1/merchant/delivery/dispatches/:dispatchId',{preHandler:manageGuard(app),schema:{body:{type:'object',additionalProperties:false,minProperties:1,properties:{driver_id:{type:'string',minLength:1,maxLength:100},notes:{type:['string','null'],maxLength:2000},cancel:{type:'boolean'},reason:{type:['string','null'],maxLength:1000}}}}},async request=>{
  const store=await merchantStore(app,request);let result;
  await app.db.transaction(async client=>{const current=await dispatchByRef(client,request.auth.tenantId,store.id,request.params.dispatchId,{lock:true});if(terminalDispatch.has(current.status))throw errors.conflict('DELIVERY_DISPATCH_TERMINAL','Delivered or cancelled dispatch assignments cannot be changed');let driver=current.driver_id,eventType='NOTE',toStatus=current.status;if(request.body.cancel===true){toStatus='CANCELLED';eventType='CANCELLED';}else if(request.body.driver_id){const next=await driverByRef(client,request.auth.tenantId,store.id,request.body.driver_id,{active:true});driver=next.id;if(driver!==current.driver_id)eventType='REASSIGNED';}
   await client.query(`UPDATE delivery_dispatches SET driver_id=$1,status=$2,notes=$3,cancelled_at=CASE WHEN $2='CANCELLED' THEN COALESCE(cancelled_at,now()) ELSE cancelled_at END,cancellation_reason=CASE WHEN $2='CANCELLED' THEN $4 ELSE cancellation_reason END,updated_at=now() WHERE id=$5`,[driver,toStatus,request.body.notes!==undefined?(request.body.notes?.trim()||null):current.notes,request.body.reason?.trim()||null,current.id]);await client.query(`INSERT INTO delivery_dispatch_events(tenant_id,store_id,dispatch_id,event_type,actor_type,actor_id,from_driver_id,to_driver_id,from_status,to_status,reason,request_id) VALUES($1,$2,$3,$4,'MERCHANT',$5,$6,$7,$8,$9,$10,$11)`,[request.auth.tenantId,store.id,current.id,eventType,request.auth.actorId,current.driver_id,driver,current.status,toStatus,request.body.reason?.trim()||request.body.notes?.trim()||null,request.id]);await writeAudit(client,{tenantId:request.auth.tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:eventType==='REASSIGNED'?'delivery.dispatch.reassign':eventType==='CANCELLED'?'delivery.dispatch.cancel':'delivery.dispatch.note',targetType:'delivery_dispatch',targetId:current.id,metadata:{from_status:current.status,to_status:toStatus},requestIp:request.ip,requestId:request.id});result=(await client.query(`${dispatchSelect} WHERE x.id=$1`,[current.id])).rows[0];});return {data:{dispatch:result}};
 });
}
