import { errors } from '../../core/errors.js';
import { PERMISSIONS } from '../../core/permissions.js';
import { publicId, uuid } from '../../core/identifiers.js';
import { writeAudit } from '../../core/audit.js';
import { resolveStore } from '../catalog/service.js';
import { confirmPayment, failPayment, paymentDetails } from './service.js';

const storeHeader=(request)=>request.headers['x-store-id']||null;

export async function merchantPaymentRoutes(app){
  app.get('/v1/merchant/payment-methods',{preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.PAYMENTS_READ)]},async(request)=>{
    const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});
    const rows=await app.db.query(`SELECT public_id AS id,code,name,provider_type,provider_key,status,instructions,public_config,sort_order,created_at,updated_at FROM payment_methods WHERE tenant_id=$1 AND store_id=$2 ORDER BY sort_order,created_at`,[request.auth.tenantId,store.id]);
    return {data:{store:{id:store.public_id,name:store.name},payment_methods:rows.rows}};
  });

  app.post('/v1/merchant/payment-methods',{preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.PAYMENTS_MANAGE)],schema:{body:{type:'object',additionalProperties:false,required:['code','name','provider_type'],properties:{code:{type:'string',minLength:1,maxLength:60},name:{type:'string',minLength:1,maxLength:120},provider_type:{type:'string',enum:['MANUAL','BANK_TRANSFER','CASH_ON_DELIVERY','EXTERNAL']},provider_key:{type:'string',maxLength:80},status:{type:'string',enum:['ACTIVE','INACTIVE']},instructions:{type:'string',maxLength:3000},public_config:{type:'object'},sort_order:{type:'integer',minimum:-10000,maximum:10000}}}}},async(request,reply)=>{
    const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});const id=uuid();const pid=publicId('paym');
    await app.db.transaction(async(client)=>{await client.query(`INSERT INTO payment_methods(id,public_id,tenant_id,store_id,code,name,provider_type,provider_key,status,instructions,public_config,sort_order) VALUES($1,$2,$3,$4,upper($5),$6,$7,$8,$9,$10,$11::jsonb,$12)`,[id,pid,request.auth.tenantId,store.id,request.body.code.trim(),request.body.name.trim(),request.body.provider_type,request.body.provider_key||null,request.body.status||'ACTIVE',request.body.instructions||null,JSON.stringify(request.body.public_config||{}),request.body.sort_order||0]);await writeAudit(client,{tenantId:request.auth.tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'payment.method.create',targetType:'payment_method',targetId:id,metadata:{public_id:pid,code:request.body.code.trim().toUpperCase()},requestIp:request.ip,requestId:request.id});});
    return reply.code(201).send({data:{payment_method:(await app.db.query(`SELECT public_id AS id,code,name,provider_type,provider_key,status,instructions,public_config,sort_order FROM payment_methods WHERE id=$1`,[id])).rows[0]}});
  });

  app.patch('/v1/merchant/payment-methods/:methodId',{preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.PAYMENTS_MANAGE)],schema:{body:{type:'object',additionalProperties:false,minProperties:1,properties:{name:{type:'string',minLength:1,maxLength:120},status:{type:'string',enum:['ACTIVE','INACTIVE']},instructions:{type:['string','null'],maxLength:3000},public_config:{type:'object'},sort_order:{type:'integer',minimum:-10000,maximum:10000}}}}},async(request)=>{
    const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});const found=await app.db.query(`SELECT * FROM payment_methods WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3`,[request.auth.tenantId,store.id,request.params.methodId]);if(!found.rowCount)throw errors.notFound('PAYMENT_METHOD_NOT_FOUND','Payment method not found');const current=found.rows[0];
    await app.db.query(`UPDATE payment_methods SET name=$1,status=$2,instructions=$3,public_config=$4::jsonb,sort_order=$5,updated_at=now() WHERE id=$6`,[request.body.name?.trim()??current.name,request.body.status??current.status,request.body.instructions!==undefined?request.body.instructions:current.instructions,JSON.stringify(request.body.public_config??current.public_config),request.body.sort_order??current.sort_order,current.id]);return {data:{payment_method:(await app.db.query(`SELECT public_id AS id,code,name,provider_type,provider_key,status,instructions,public_config,sort_order FROM payment_methods WHERE id=$1`,[current.id])).rows[0]}};
  });

  app.get('/v1/merchant/payments',{preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.PAYMENTS_READ)],schema:{querystring:{type:'object',additionalProperties:false,properties:{status:{type:'string',maxLength:40},limit:{type:'integer',minimum:1,maximum:200,default:50},offset:{type:'integer',minimum:0,maximum:1000000,default:0}}}}},async(request)=>{
    const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});const values=[request.auth.tenantId,store.id];let where='op.tenant_id=$1 AND op.store_id=$2';if(request.query.status){values.push(request.query.status);where+=` AND op.status=$${values.length}`;}values.push(request.query.limit||50,request.query.offset||0);const rows=await app.db.query(`SELECT op.public_id AS id,o.public_id AS order_id,o.order_number,c.public_id AS customer_id,op.status,op.amount,op.currency,pm.code AS payment_method_code,pm.name AS payment_method_name,op.provider_reference,op.paid_at,op.failed_at,op.created_at FROM order_payments op JOIN orders o ON o.id=op.order_id AND o.tenant_id=op.tenant_id AND o.store_id=op.store_id JOIN customers c ON c.id=o.customer_id AND c.tenant_id=o.tenant_id LEFT JOIN payment_methods pm ON pm.id=op.payment_method_id AND pm.tenant_id=op.tenant_id AND pm.store_id=op.store_id WHERE ${where} ORDER BY op.created_at DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values);return {data:{payments:rows.rows,limit:request.query.limit||50,offset:request.query.offset||0}};
  });

  app.get('/v1/merchant/orders/:orderRef/payment',{preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.PAYMENTS_READ)]},async(request)=>({data:{payment:await paymentDetails(app.db,request.auth.tenantId,request.params.orderRef)}}));

  app.post('/v1/merchant/orders/:orderRef/payment/confirm',{preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.PAYMENTS_MANAGE)],schema:{body:{type:'object',additionalProperties:false,properties:{provider_reference:{type:'string',maxLength:240}}}}},async(request)=>{
    const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});await app.db.transaction(async(client)=>{const found=await client.query(`SELECT * FROM orders WHERE tenant_id=$1 AND store_id=$2 AND (public_id=$3 OR order_number=$3) FOR UPDATE`,[request.auth.tenantId,store.id,request.params.orderRef]);if(!found.rowCount)throw errors.notFound('ORDER_NOT_FOUND','Order not found');const order=found.rows[0];await confirmPayment(client,{tenantId:request.auth.tenantId,storeId:store.id,order,providerReference:request.body?.provider_reference||null,requestId:request.id});await writeAudit(client,{tenantId:request.auth.tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'payment.confirm',targetType:'order',targetId:order.id,metadata:{order_number:order.order_number,provider_reference:request.body?.provider_reference||null},requestIp:request.ip,requestId:request.id});});return {data:{payment:await paymentDetails(app.db,request.auth.tenantId,request.params.orderRef)}};
  });

  app.post('/v1/merchant/orders/:orderRef/payment/fail',{preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.PAYMENTS_MANAGE)],schema:{body:{type:'object',additionalProperties:false,properties:{failure_code:{type:'string',maxLength:120},failure_message:{type:'string',maxLength:1000}}}}},async(request)=>{
    const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});await app.db.transaction(async(client)=>{const found=await client.query(`SELECT * FROM orders WHERE tenant_id=$1 AND store_id=$2 AND (public_id=$3 OR order_number=$3) FOR UPDATE`,[request.auth.tenantId,store.id,request.params.orderRef]);if(!found.rowCount)throw errors.notFound('ORDER_NOT_FOUND','Order not found');const order=found.rows[0];await failPayment(client,{tenantId:request.auth.tenantId,storeId:store.id,order,failureCode:request.body?.failure_code||null,failureMessage:request.body?.failure_message||null,requestId:request.id});await writeAudit(client,{tenantId:request.auth.tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'payment.fail',targetType:'order',targetId:order.id,metadata:{order_number:order.order_number,failure_code:request.body?.failure_code||null},requestIp:request.ip,requestId:request.id});});return {data:{payment:await paymentDetails(app.db,request.auth.tenantId,request.params.orderRef)}};
  });
}
