-- Luke Shop Backend v0.9.0 — Experience Engine v2 + Commerce Workflow
-- Additive migration. Migrations 001-009 remain immutable.

ALTER TABLE storefront_experience_versions
  ADD COLUMN IF NOT EXISTS schema_version integer NOT NULL DEFAULT 2;

ALTER TABLE promotions
  ADD COLUMN IF NOT EXISTS schedule_timezone text;

ALTER TABLE promotions DROP CONSTRAINT IF EXISTS promotions_status_check;
ALTER TABLE promotions ADD CONSTRAINT promotions_status_check
  CHECK (status IN ('DRAFT','SCHEDULED','ACTIVE','PAUSED','EXPIRED','ARCHIVED'));
ALTER TABLE promotions DROP CONSTRAINT IF EXISTS promotions_schedule_window_check;
ALTER TABLE promotions ADD CONSTRAINT promotions_schedule_window_check
  CHECK (starts_at IS NULL OR ends_at IS NULL OR ends_at > starts_at);

CREATE TABLE IF NOT EXISTS platform_typography_presets (
  key text PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  status text NOT NULL CHECK (status IN ('ACTIVE','INACTIVE')),
  heading_stack text NOT NULL,
  body_stack text NOT NULL,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO platform_typography_presets(key,name,category,status,heading_stack,body_stack,settings) VALUES
('IOS_SYSTEM','iPhone / iOS System','SYSTEM','ACTIVE','-apple-system, BlinkMacSystemFont, "SF Pro Display", "Helvetica Neue", Arial, sans-serif','-apple-system, BlinkMacSystemFont, "SF Pro Text", "Helvetica Neue", Arial, sans-serif','{"heading_weight":700,"body_weight":400,"letter_spacing":"tight"}'::jsonb),
('SYSTEM_MINIMAL','System Minimal','SYSTEM','ACTIVE','system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif','system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif','{"heading_weight":700,"body_weight":400}'::jsonb),
('MODERN_SANS','Modern Sans','SANS','ACTIVE','Inter, ui-sans-serif, system-ui, sans-serif','Inter, ui-sans-serif, system-ui, sans-serif','{"heading_weight":800,"body_weight":400}'::jsonb),
('CLEAN_COMMERCE','Clean Commerce','SANS','ACTIVE','Manrope, ui-sans-serif, system-ui, sans-serif','Manrope, ui-sans-serif, system-ui, sans-serif','{"heading_weight":750,"body_weight":400}'::jsonb),
('GEOMETRIC','Geometric','SANS','ACTIVE','Avenir Next, Avenir, Montserrat, ui-sans-serif, sans-serif','Avenir Next, Avenir, ui-sans-serif, sans-serif','{"heading_weight":700,"body_weight":400}'::jsonb),
('FRIENDLY','Friendly','SANS','ACTIVE','Nunito, ui-rounded, system-ui, sans-serif','Nunito, ui-rounded, system-ui, sans-serif','{"heading_weight":800,"body_weight":400}'::jsonb),
('HUMANIST','Humanist','SANS','ACTIVE','Gill Sans, Gill Sans MT, Calibri, sans-serif','Calibri, Candara, Segoe, sans-serif','{"heading_weight":700,"body_weight":400}'::jsonb),
('EDITORIAL','Editorial','SERIF','ACTIVE','Georgia, Times New Roman, serif','system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif','{"heading_weight":700,"body_weight":400}'::jsonb),
('LUXURY_SERIF','Luxury Serif','SERIF','ACTIVE','Didot, Bodoni MT, Georgia, serif','Avenir Next, Avenir, system-ui, sans-serif','{"heading_weight":600,"body_weight":400}'::jsonb),
('CLASSIC_SERIF','Classic Serif','SERIF','ACTIVE','Baskerville, Georgia, Times New Roman, serif','Georgia, Times New Roman, serif','{"heading_weight":600,"body_weight":400}'::jsonb),
('TECHNICAL','Technical','SYSTEM','ACTIVE','Roboto, Arial, sans-serif','Roboto, Arial, sans-serif','{"heading_weight":700,"body_weight":400}'::jsonb),
('COMPACT_UI','Compact UI','SYSTEM','ACTIVE','Segoe UI, Arial, sans-serif','Segoe UI, Arial, sans-serif','{"heading_weight":700,"body_weight":400,"density":"compact"}'::jsonb)
ON CONFLICT (key) DO UPDATE SET name=EXCLUDED.name,category=EXCLUDED.category,status=EXCLUDED.status,heading_stack=EXCLUDED.heading_stack,body_stack=EXCLUDED.body_stack,settings=EXCLUDED.settings,updated_at=now();

-- Expand the platform template library. These configs contain only safe design tokens and layout keys.
INSERT INTO platform_storefront_templates(public_id,key,name,business_type,status,config) VALUES
('tpl_fashion_luxury','FASHION_LUXURY','Fashion Luxury','FASHION','ACTIVE','{"schema_version":2,"theme":{"preset":"luxury","primary":"#111111","secondary":"#6b4f2a","accent":"#c6a15b","background":"#fbfaf7","surface":"#ffffff","text":"#161616","muted_text":"#72706b","radius":"small","card_style":"editorial","button_style":"pill","density":"comfortable"},"typography":{"preset":"LUXURY_SERIF","heading_scale":"large","body_scale":"normal","letter_spacing":"normal"},"layout":{"header":"centered_logo","hero":"split","categories":"image_tiles","product_grid":"editorial","product_card":"minimal","mobile_nav":"standard"},"branding":{"hero_title":"The new collection","hero_subtitle":"Timeless pieces, carefully selected."},"navigation":["home","explore","cart","orders","profile"],"home":{"sections":[{"id":"hero","type":"hero","enabled":true},{"id":"categories","type":"categories","enabled":true,"limit":6},{"id":"featured","type":"featured_products","enabled":true,"limit":8}]}}'::jsonb),
('tpl_streetwear_bold','STREETWEAR_BOLD','Streetwear Bold','FASHION','ACTIVE','{"schema_version":2,"theme":{"preset":"bold","primary":"#7c3aed","secondary":"#09090b","accent":"#facc15","background":"#f5f5f5","surface":"#ffffff","text":"#09090b","muted_text":"#71717a","radius":"large","card_style":"bold","button_style":"solid","density":"comfortable"},"typography":{"preset":"GEOMETRIC","heading_scale":"large","body_scale":"normal","letter_spacing":"tight"},"layout":{"header":"compact","hero":"full_width","categories":"chips","product_grid":"four","product_card":"bold","mobile_nav":"standard"},"branding":{"hero_title":"Drop live now","hero_subtitle":"New pieces. Limited quantities."},"navigation":["home","explore","cart","orders","profile"],"home":{"sections":[{"id":"hero","type":"hero","enabled":true},{"id":"new","type":"new_arrivals","enabled":true,"limit":8},{"id":"categories","type":"categories","enabled":true,"limit":8}]}}'::jsonb),
('tpl_cafe_warm','CAFE_WARM','Café Warm','RESTAURANT','ACTIVE','{"schema_version":2,"theme":{"preset":"cafe","primary":"#9a5b36","secondary":"#3f2d24","accent":"#d8a46d","background":"#fbf5ee","surface":"#fffdf9","text":"#30251f","muted_text":"#7e6b60","radius":"large","card_style":"soft","button_style":"pill","density":"comfortable"},"typography":{"preset":"FRIENDLY","heading_scale":"normal","body_scale":"normal","letter_spacing":"normal"},"layout":{"header":"logo_left","hero":"split","categories":"cards","product_grid":"three","product_card":"soft","mobile_nav":"standard"},"branding":{"hero_title":"Made fresh today","hero_subtitle":"Coffee, pastries and favorites from the kitchen."},"navigation":["home","explore","cart","orders","profile"],"home":{"sections":[{"id":"hero","type":"hero","enabled":true},{"id":"categories","type":"categories","enabled":true,"limit":8},{"id":"featured","type":"featured_products","enabled":true,"limit":8}]}}'::jsonb),
('tpl_fast_food','FAST_FOOD','Fast Food','RESTAURANT','ACTIVE','{"schema_version":2,"theme":{"preset":"fast_food","primary":"#dc2626","secondary":"#171717","accent":"#f59e0b","background":"#fff7ed","surface":"#ffffff","text":"#171717","muted_text":"#737373","radius":"large","card_style":"bold","button_style":"solid","density":"compact"},"typography":{"preset":"MODERN_SANS","heading_scale":"large","body_scale":"normal","letter_spacing":"tight"},"layout":{"header":"compact","hero":"featured_product","categories":"horizontal","product_grid":"three","product_card":"quick_add","mobile_nav":"standard"},"branding":{"hero_title":"Hot, fast, ready","hero_subtitle":"Order your favorites in a few taps."},"navigation":["home","explore","cart","orders","profile"],"home":{"sections":[{"id":"hero","type":"hero","enabled":true},{"id":"categories","type":"categories","enabled":true,"limit":10},{"id":"featured","type":"featured_products","enabled":true,"limit":8},{"id":"promo","type":"promotion_banner","enabled":true}]}}'::jsonb),
('tpl_grocery_clean','GROCERY_CLEAN','Grocery Clean','GROCERY','ACTIVE','{"schema_version":2,"theme":{"preset":"grocery","primary":"#15803d","secondary":"#14532d","accent":"#84cc16","background":"#f7fee7","surface":"#ffffff","text":"#1f2937","muted_text":"#6b7280","radius":"medium","card_style":"clean","button_style":"solid","density":"compact"},"typography":{"preset":"CLEAN_COMMERCE","heading_scale":"normal","body_scale":"normal","letter_spacing":"normal"},"layout":{"header":"search_first","hero":"minimal","categories":"cards","product_grid":"four","product_card":"compact","mobile_nav":"standard"},"branding":{"hero_title":"Fresh essentials, delivered","hero_subtitle":"Everyday groceries and household favorites."},"navigation":["home","explore","cart","orders","profile"],"home":{"sections":[{"id":"categories","type":"categories","enabled":true,"limit":10},{"id":"featured","type":"featured_products","enabled":true,"limit":12},{"id":"promo","type":"promotion_banner","enabled":true}]}}'::jsonb),
('tpl_electronics_pro','ELECTRONICS_PRO','Electronics Pro','ELECTRONICS','ACTIVE','{"schema_version":2,"theme":{"preset":"electronics","primary":"#2563eb","secondary":"#0f172a","accent":"#06b6d4","background":"#f8fafc","surface":"#ffffff","text":"#0f172a","muted_text":"#64748b","radius":"medium","card_style":"technical","button_style":"solid","density":"compact"},"typography":{"preset":"TECHNICAL","heading_scale":"normal","body_scale":"normal","letter_spacing":"normal"},"layout":{"header":"search_first","hero":"split","categories":"chips","product_grid":"four","product_card":"technical","mobile_nav":"standard"},"branding":{"hero_title":"Technology for every day","hero_subtitle":"Discover devices, tools and accessories."},"navigation":["home","explore","cart","orders","profile"],"home":{"sections":[{"id":"hero","type":"hero","enabled":true},{"id":"categories","type":"categories","enabled":true,"limit":10},{"id":"featured","type":"featured_products","enabled":true,"limit":12}]}}'::jsonb),
('tpl_digital_creator','DIGITAL_CREATOR','Digital Creator','DIGITAL','ACTIVE','{"schema_version":2,"theme":{"preset":"creator","primary":"#ec4899","secondary":"#312e81","accent":"#8b5cf6","background":"#faf5ff","surface":"#ffffff","text":"#231942","muted_text":"#776f86","radius":"large","card_style":"editorial","button_style":"pill","density":"comfortable"},"typography":{"preset":"EDITORIAL","heading_scale":"large","body_scale":"normal","letter_spacing":"normal"},"layout":{"header":"centered_logo","hero":"full_width","categories":"image_tiles","product_grid":"three","product_card":"editorial","mobile_nav":"standard"},"branding":{"hero_title":"Create. Share. Sell.","hero_subtitle":"Digital work, collections and premium downloads."},"navigation":["home","explore","cart","orders","profile"],"home":{"sections":[{"id":"hero","type":"hero","enabled":true},{"id":"featured","type":"featured_products","enabled":true,"limit":9},{"id":"categories","type":"categories","enabled":true,"limit":6}]}}'::jsonb),
('tpl_ios_minimal','IOS_MINIMAL','iOS Minimal','GENERAL','ACTIVE','{"schema_version":2,"theme":{"preset":"ios_minimal","primary":"#007aff","secondary":"#1c1c1e","accent":"#5856d6","background":"#f2f2f7","surface":"#ffffff","text":"#1c1c1e","muted_text":"#6e6e73","radius":"large","card_style":"soft","button_style":"pill","density":"comfortable"},"typography":{"preset":"IOS_SYSTEM","heading_scale":"normal","body_scale":"normal","letter_spacing":"normal"},"layout":{"header":"compact","hero":"minimal","categories":"cards","product_grid":"two","product_card":"soft","mobile_nav":"ios"},"branding":{"hero_title":"Simple shopping, beautifully presented","hero_subtitle":"A clean customer experience inspired by native iPhone interfaces."},"navigation":["home","explore","cart","orders","profile"],"home":{"sections":[{"id":"hero","type":"hero","enabled":true},{"id":"categories","type":"categories","enabled":true,"limit":6},{"id":"featured","type":"featured_products","enabled":true,"limit":8}]}}'::jsonb)
ON CONFLICT (key) DO UPDATE SET name=EXCLUDED.name,business_type=EXCLUDED.business_type,status=EXCLUDED.status,config=EXCLUDED.config,updated_at=now();
