import { errors } from '../../core/errors.js';
import { publicId, uuid } from '../../core/identifiers.js';
import { writeAudit } from '../../core/audit.js';
import { resolveStore } from '../catalog/service.js';
import { assertOrderTransition, money } from '../orders/service.js';
import { paymentDetails } from '../payments/service.js';
import { fulfillmentDetails, resolveDeliverySelection } from '../delivery/service.js';
import { digitalDeliveryRoutes } from '../digital-delivery/routes.js';
const storeHeader=(r)=>r.headers['x-store-id']||null;
const quoteAddressSchema={type:'object',additionalProperties:false,required:['recipient_name','country_code','city','address_line_1'],properties:{recipient_name:{type:'string',minLength:1,maxLength:160},phone:{type:'string',maxLength:60},country_code:{type:'string',pattern:'^[A-Z]{2}$'},state:{type:'string',maxLength:160},city:{type:'string',minLength:1,maxLength:160},postal_code:{type:'string',maxLength:40},address_line_1:{type:'string',minLength:1,maxLength:300},address_line_2:{type:'string',maxLength:300},delivery_note:{type:'string',maxLength:1000},latitude:{type:['number','null'],minimum:-90,maximum:90},longitude:{type:['number','null'],minimum:-180,maximum:180},accuracy_meters:{type:['number','null'],minimum:0,maximum:100000},location_source:{type:['string','null'],enum:['GPS','MAP_PIN','ADDRESS',null]},formatted_address:{type:['string','null'],maxLength:600}}};
export async function customerCommerceRoutes(app){
 await digitalDeliveryRoutes(app);
 app.get('/v1/storefront/payment-methods',{preHandler:[app.requireTenant]},async(request)=>{const store=await resolveStore(app.db,request.tenant.id,storeHeader(request));const rows=await app.db.query(`SELECT public_id AS id,code,name,provider_type,provider_key,instructions,public_config,sort_order FROM payment_methods WHERE tenant_id=$1 AND store_id=$2 AND status='ACTIVE' ORDER BY sort_order,created_at`,[request.tenant.id,store.id]);return {data:{payment_methods:rows.rows}};});
 app.get('/v1/storefront/delivery-methods',{preHandler:[app.requireTenant]},async(request)=>{const store=await resolveStore(app.db,request.tenant.id,storeHeader(request));const rows=await app.db.query(`SELECT public_id AS id,code,name,fulfillment_mode,pricing_mode,zone_no_match_policy,flat_fee,free_over,min_order,estimated_min_minutes,estimated_max_minutes,public_config,sort_order FROM delivery_methods WHERE tenant_id=$1 AND store_id=$2 AND status='ACTIVE' ORDER BY sort_order,created_at`,[request.tenant.id,store.id]);return {data:{delivery_methods:rows.rows}};});
 app.post('/v1/customer/delivery/quote',{preHandler:[app.requireCustomerAuth],schema:{body:{type:'object',additionalProperties:false,required:['delivery_method_id','shipping_address'],properties:{delivery_method_id:{type:'string',minLength:1,maxLength:140},shipping_address:quoteAddressSchema}}}},async request=>{
  const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request));const settings=await app.db.query('SELECT currency FROM tenant_settings WHERE tenant_id=$1',[request.auth.tenantId]);if(!settings.rowCount)throw errors.conflict('TENANT_SETTINGS_MISSING','Tenant settings are missing');
  const quote=await app.db.transaction(async client=>{
   const cart=await client.query(`SELECT * FROM carts WHERE tenant_id=$1 AND store_id=$2 AND customer_id=$3 AND status='ACTIVE'`,[request.auth.tenantId,store.id,request.auth.actorId]);if(!cart.rowCount)throw errors.notFound('CART_NOT_FOUND','Active cart not found');
   const rows=await client.query(`SELECT ci.*,p.product_type FROM cart_items ci JOIN products p ON p.id=ci.product_id AND p.tenant_id=ci.tenant_id AND p.store_id=ci.store_id WHERE ci.tenant_id=$1 AND ci.store_id=$2 AND ci.cart_id=$3 ORDER BY ci.created_at,ci.id`,[request.auth.tenantId,store.id,cart.rows[0].id]);if(!rows.rowCount)throw errors.badRequest('CART_EMPTY','Cart is empty');
   const subtotal=money(rows.rows.reduce((sum,row)=>sum+Number(row.line_total),0));const selection=await resolveDeliverySelection(client,{tenantId:request.auth.tenantId,storeId:store.id,cartItems:rows.rows,subtotal,deliveryMethodRef:request.body.delivery_method_id,shippingAddress:request.body.shipping_address});
   if(!selection.method)throw errors.conflict('DELIVERY_NOT_REQUIRED','The current cart does not require a physical delivery method');
   return {delivery_method_id:selection.method.public_id,delivery_method_code:selection.method.code,delivery_method_name:selection.method.name,fulfillment_mode:selection.mode,pricing_mode:selection.pricingSnapshot?.pricing_mode||'BASELINE',pricing_source:selection.pricingSnapshot?.pricing_source||'BASELINE',zone:selection.pricingSnapshot?.zone||null,base_delivery_total:money(selection.baseDeliveryTotal),vip_discount:money(selection.vip?.deliveryDiscount||0),delivery_total:money(selection.deliveryTotal),currency:settings.rows[0].currency,estimated_min_minutes:selection.rate?.estimated_min_minutes??selection.method.estimated_min_minutes??null,estimated_max_minutes:selection.rate?.estimated_max_minutes??selection.method.estimated_max_minutes??null};
  });return {data:{delivery_quote:quote}};
 });
 app.get('/v1/customer/orders/:orderRef/payment',{preHandler:[app.requireCustomerAuth]},async(request)=>({data:{payment:await paymentDetails(app.db,request.auth.tenantId,request.params.orderRef,{customerId:request.auth.actorId})}}));
 app.get('/v1/customer/orders/:orderRef/fulfillments',{preHandler:[app.requireCustomerAuth]},async(request)=>({data:{fulfillments:await fulfillmentDetails(app.db,request.auth.tenantId,request.params.orderRef,{customerId:request.auth.actorId})}}));
 app.post('/v1/customer/orders/:orderRef/payment/retry',{preHandler:[app.requireCustomerAuth],schema:{body:{type:'object',additionalProperties:false,required:['idempotency_key'],properties:{idempotency_key:{type:'string',minLength:8,maxLength:160}}}}},async(request)=>{
   await app.db.transaction(async(client)=>{const found=await client.query(`SELECT * FROM orders WHERE tenant_id=$1 AND customer_id=$2 AND (public_id=$3 OR order_number=$3) FOR UPDATE`,[request.auth.tenantId,request.auth.actorId,request.params.orderRef]);if(!found.rowCount)throw errors.notFound('ORDER_NOT_FOUND','Order not found');const order=found.rows[0];if(order.status!=='PAYMENT_FAILED')throw errors.conflict('PAYMENT_RETRY_NOT_ALLOWED','Only a failed payment can be retried');if(order.reservation_expires_at&&new Date(order.reservation_expires_at)<=new Date())throw errors.conflict('PAYMENT_RESERVATION_EXPIRED','Inventory reservation has expired');assertOrderTransition(order.order_type,order.status,'PENDING_PAYMENT');const payment=await client.query(`SELECT * FROM order_payments WHERE tenant_id=$1 AND store_id=$2 AND order_id=$3 FOR UPDATE`,[request.auth.tenantId,order.store_id,order.id]);if(!payment.rowCount)throw errors.notFound('PAYMENT_NOT_FOUND','Payment not found');const existing=await client.query(`SELECT id FROM payment_attempts WHERE tenant_id=$1 AND store_id=$2 AND payment_id=$3 AND idempotency_key=$4`,[request.auth.tenantId,order.store_id,payment.rows[0].id,request.body.idempotency_key]);if(existing.rowCount)return;const next=await client.query(`SELECT COALESCE(max(attempt_no),0)::int+1 AS n FROM payment_attempts WHERE tenant_id=$1 AND store_id=$2 AND payment_id=$3`,[request.auth.tenantId,order.store_id,payment.rows[0].id]);await client.query(`INSERT INTO payment_attempts(id,public_id,tenant_id,store_id,payment_id,attempt_no,status,idempotency_key,request_summary) VALUES($1,$2,$3,$4,$5,$6,'CREATED',$7,'{"source":"customer_retry"}'::jsonb)`,[uuid(),publicId('pat'),request.auth.tenantId,order.store_id,payment.rows[0].id,next.rows[0].n,request.body.idempotency_key]);await client.query(`UPDATE order_payments SET status='PENDING',failure_code=NULL,failure_message=NULL,failed_at=NULL,updated_at=now() WHERE id=$1`,[payment.rows[0].id]);await client.query(`UPDATE orders SET status='PENDING_PAYMENT',payment_status='PENDING',reservation_expires_at=GREATEST(COALESCE(reservation_expires_at,now()),now()+interval '30 minutes'),updated_at=now() WHERE id=$1`,[order.id]);await client.query(`INSERT INTO order_status_history(tenant_id,store_id,order_id,from_status,to_status,reason,actor_type,actor_id,request_id) VALUES($1,$2,$3,'PAYMENT_FAILED','PENDING_PAYMENT','Customer payment retry','CUSTOMER',$4,$5)`,[request.auth.tenantId,order.store_id,order.id,request.auth.actorId,request.id]);await writeAudit(client,{tenantId:request.auth.tenantId,actorType:'CUSTOMER',actorId:request.auth.actorId,action:'payment.retry',targetType:'order',targetId:order.id,metadata:{order_number:order.order_number},requestIp:request.ip,requestId:request.id});});return {data:{payment:await paymentDetails(app.db,request.auth.tenantId,request.params.orderRef,{customerId:request.auth.actorId})}};
 });
}
