import { errors } from '../../core/errors.js';
import { PERMISSIONS } from '../../core/permissions.js';
import { publicId, uuid } from '../../core/identifiers.js';
import { writeAudit } from '../../core/audit.js';
import { resolveStore } from '../catalog/service.js';
const storeHeader=(r)=>r.headers['x-store-id']||null;
const promotionStatuses=['DRAFT','SCHEDULED','ACTIVE','PAUSED','EXPIRED','ARCHIVED'];

function effectiveStatus(row,now=new Date()){
  if(['DRAFT','PAUSED','ARCHIVED'].includes(row.status))return row.status;
  if(row.ends_at&&new Date(row.ends_at)<=now)return 'EXPIRED';
  if(row.starts_at&&new Date(row.starts_at)>now)return 'SCHEDULED';
  return 'ACTIVE';
}
function assertWindow(startsAt,endsAt){if(startsAt&&endsAt&&new Date(endsAt)<=new Date(startsAt))throw errors.badRequest('PROMOTION_SCHEDULE_INVALID','Promotion end date/time must be after the start date/time');}
function shape(row){return {...row,effective_status:effectiveStatus(row)};}
async function tenantTimezone(db,tenantId){const r=await db.query('SELECT timezone FROM tenant_settings WHERE tenant_id=$1',[tenantId]);return r.rows[0]?.timezone||'UTC';}
async function detail(db,tenantId,storeId,pid){
 const p=await db.query(`SELECT public_id AS id,name,promotion_type,status,automatic,value,buy_quantity,get_quantity,min_subtotal,max_discount,first_order_only,starts_at,ends_at,schedule_timezone,usage_limit,per_customer_limit,metadata,created_at,updated_at FROM promotions WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3`,[tenantId,storeId,pid]);
 if(!p.rowCount)throw errors.notFound('PROMOTION_NOT_FOUND','Promotion not found');
 const codes=await db.query(`SELECT pc.public_id AS id,pc.code,pc.status,pc.usage_limit FROM promotion_codes pc JOIN promotions p ON p.id=pc.promotion_id AND p.tenant_id=pc.tenant_id AND p.store_id=pc.store_id WHERE pc.tenant_id=$1 AND pc.store_id=$2 AND p.public_id=$3 ORDER BY pc.created_at`,[tenantId,storeId,pid]);
 const targets=await db.query(`SELECT pt.target_type,p.public_id AS product_id,p.name AS product_name,c.public_id AS category_id,c.name AS category_name FROM promotion_targets pt JOIN promotions pr ON pr.id=pt.promotion_id AND pr.tenant_id=pt.tenant_id AND pr.store_id=pt.store_id LEFT JOIN products p ON p.id=pt.product_id AND p.tenant_id=pt.tenant_id AND p.store_id=pt.store_id LEFT JOIN categories c ON c.id=pt.category_id AND c.tenant_id=pt.tenant_id AND c.store_id=pt.store_id WHERE pt.tenant_id=$1 AND pt.store_id=$2 AND pr.public_id=$3`,[tenantId,storeId,pid]);
 return {...shape(p.rows[0]),codes:codes.rows,targets:targets.rows};
}
export async function merchantPromotionRoutes(app){
 app.get('/v1/merchant/promotions',{preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.PROMOTIONS_READ)]},async(request)=>{
   const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});
   const [rows,timezone]=await Promise.all([app.db.query(`SELECT public_id AS id,name,promotion_type,status,automatic,value,buy_quantity,get_quantity,min_subtotal,max_discount,first_order_only,starts_at,ends_at,schedule_timezone,usage_limit,per_customer_limit,created_at,updated_at FROM promotions WHERE tenant_id=$1 AND store_id=$2 ORDER BY created_at DESC`,[request.auth.tenantId,store.id]),tenantTimezone(app.db,request.auth.tenantId)]);
   return {data:{promotions:rows.rows.map(shape),timezone}};
 });
 app.post('/v1/merchant/promotions',{preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.PROMOTIONS_WRITE)],schema:{body:{type:'object',additionalProperties:false,required:['name','promotion_type'],properties:{name:{type:'string',minLength:1,maxLength:160},promotion_type:{type:'string',enum:['PERCENTAGE','FIXED_AMOUNT','FREE_DELIVERY','BOGO']},status:{type:'string',enum:promotionStatuses},automatic:{type:'boolean'},value:{type:'number',minimum:0},buy_quantity:{type:['integer','null'],minimum:1},get_quantity:{type:['integer','null'],minimum:1},min_subtotal:{type:'number',minimum:0},max_discount:{type:['number','null'],minimum:0},first_order_only:{type:'boolean'},starts_at:{type:['string','null'],format:'date-time'},ends_at:{type:['string','null'],format:'date-time'},schedule_timezone:{type:['string','null'],maxLength:64},usage_limit:{type:['integer','null'],minimum:1},per_customer_limit:{type:['integer','null'],minimum:1},metadata:{type:'object'}}}}},async(request,reply)=>{
   const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});
   if(request.body.promotion_type==='PERCENTAGE'&&Number(request.body.value||0)>100)throw errors.badRequest('PROMOTION_VALUE_INVALID','Percentage cannot exceed 100');
   if(request.body.promotion_type==='BOGO'&&(!request.body.buy_quantity||!request.body.get_quantity))throw errors.badRequest('PROMOTION_BOGO_INVALID','BOGO requires buy_quantity and get_quantity');
   assertWindow(request.body.starts_at,request.body.ends_at);
   const timezone=request.body.schedule_timezone||await tenantTimezone(app.db,request.auth.tenantId);const id=uuid(),pid=publicId('promo');
   await app.db.transaction(async(client)=>{await client.query(`INSERT INTO promotions(id,public_id,tenant_id,store_id,name,promotion_type,status,automatic,value,buy_quantity,get_quantity,min_subtotal,max_discount,first_order_only,starts_at,ends_at,schedule_timezone,usage_limit,per_customer_limit,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20::jsonb)`,[id,pid,request.auth.tenantId,store.id,request.body.name.trim(),request.body.promotion_type,request.body.status||'DRAFT',request.body.automatic||false,request.body.value||0,request.body.buy_quantity??null,request.body.get_quantity??null,request.body.min_subtotal||0,request.body.max_discount??null,request.body.first_order_only||false,request.body.starts_at??null,request.body.ends_at??null,timezone,request.body.usage_limit??null,request.body.per_customer_limit??null,JSON.stringify(request.body.metadata||{})]);await writeAudit(client,{tenantId:request.auth.tenantId,actorType:'MERCHANT',actorId:request.auth.actorId,action:'promotion.create',targetType:'promotion',targetId:id,metadata:{public_id:pid,type:request.body.promotion_type,starts_at:request.body.starts_at||null,ends_at:request.body.ends_at||null,timezone},requestIp:request.ip,requestId:request.id});});
   return reply.code(201).send({data:{promotion:await detail(app.db,request.auth.tenantId,store.id,pid)}});
 });
 app.get('/v1/merchant/promotions/:promotionId',{preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.PROMOTIONS_READ)]},async(request)=>{const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});return {data:{promotion:await detail(app.db,request.auth.tenantId,store.id,request.params.promotionId)}};});
 app.post('/v1/merchant/promotions/:promotionId/codes',{preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.PROMOTIONS_WRITE)],schema:{body:{type:'object',additionalProperties:false,required:['code'],properties:{code:{type:'string',minLength:2,maxLength:80},status:{type:'string',enum:['ACTIVE','INACTIVE']},usage_limit:{type:['integer','null'],minimum:1}}}}},async(request,reply)=>{const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});const p=await app.db.query(`SELECT id FROM promotions WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3`,[request.auth.tenantId,store.id,request.params.promotionId]);if(!p.rowCount)throw errors.notFound('PROMOTION_NOT_FOUND','Promotion not found');const pid=publicId('pcode');await app.db.query(`INSERT INTO promotion_codes(id,public_id,tenant_id,store_id,promotion_id,code,status,usage_limit) VALUES($1,$2,$3,$4,$5,upper($6),$7,$8)`,[uuid(),pid,request.auth.tenantId,store.id,p.rows[0].id,request.body.code.trim(),request.body.status||'ACTIVE',request.body.usage_limit??null]);return reply.code(201).send({data:{promotion:await detail(app.db,request.auth.tenantId,store.id,request.params.promotionId)}});});
 app.post('/v1/merchant/promotions/:promotionId/targets',{preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.PROMOTIONS_WRITE)],schema:{body:{type:'object',additionalProperties:false,required:['target_type'],properties:{target_type:{type:'string',enum:['ORDER','PRODUCT','CATEGORY']},product_id:{type:'string',maxLength:140},category_id:{type:'string',maxLength:140}}}}},async(request,reply)=>{const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});const p=await app.db.query(`SELECT id FROM promotions WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3`,[request.auth.tenantId,store.id,request.params.promotionId]);if(!p.rowCount)throw errors.notFound('PROMOTION_NOT_FOUND','Promotion not found');let productId=null,categoryId=null;if(request.body.target_type==='PRODUCT'){const f=await app.db.query(`SELECT id FROM products WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3`,[request.auth.tenantId,store.id,request.body.product_id]);if(!f.rowCount)throw errors.notFound('PRODUCT_NOT_FOUND','Product not found');productId=f.rows[0].id;}if(request.body.target_type==='CATEGORY'){const f=await app.db.query(`SELECT id FROM categories WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3`,[request.auth.tenantId,store.id,request.body.category_id]);if(!f.rowCount)throw errors.notFound('CATEGORY_NOT_FOUND','Category not found');categoryId=f.rows[0].id;}await app.db.query(`INSERT INTO promotion_targets(id,tenant_id,store_id,promotion_id,target_type,product_id,category_id) VALUES($1,$2,$3,$4,$5,$6,$7)`,[uuid(),request.auth.tenantId,store.id,p.rows[0].id,request.body.target_type,productId,categoryId]);return reply.code(201).send({data:{promotion:await detail(app.db,request.auth.tenantId,store.id,request.params.promotionId)}});});
 app.patch('/v1/merchant/promotions/:promotionId',{preHandler:[app.requireMerchantAuth,app.requirePermission(PERMISSIONS.PROMOTIONS_WRITE)],schema:{body:{type:'object',additionalProperties:false,minProperties:1,properties:{name:{type:'string',minLength:1,maxLength:160},status:{type:'string',enum:promotionStatuses},automatic:{type:'boolean'},value:{type:'number',minimum:0},buy_quantity:{type:['integer','null'],minimum:1},get_quantity:{type:['integer','null'],minimum:1},min_subtotal:{type:'number',minimum:0},max_discount:{type:['number','null'],minimum:0},first_order_only:{type:'boolean'},starts_at:{type:['string','null'],format:'date-time'},ends_at:{type:['string','null'],format:'date-time'},schedule_timezone:{type:['string','null'],maxLength:64},usage_limit:{type:['integer','null'],minimum:1},per_customer_limit:{type:['integer','null'],minimum:1},metadata:{type:'object'}}}}},async(request)=>{
   const store=await resolveStore(app.db,request.auth.tenantId,storeHeader(request),{requireActive:false});const f=await app.db.query(`SELECT * FROM promotions WHERE tenant_id=$1 AND store_id=$2 AND public_id=$3`,[request.auth.tenantId,store.id,request.params.promotionId]);if(!f.rowCount)throw errors.notFound('PROMOTION_NOT_FOUND','Promotion not found');const c=f.rows[0];
   const value=request.body.value??c.value,buyQuantity=request.body.buy_quantity!==undefined?request.body.buy_quantity:c.buy_quantity,getQuantity=request.body.get_quantity!==undefined?request.body.get_quantity:c.get_quantity;
   if(c.promotion_type==='PERCENTAGE'&&Number(value)>100)throw errors.badRequest('PROMOTION_VALUE_INVALID','Percentage cannot exceed 100');if(c.promotion_type==='BOGO'&&(!buyQuantity||!getQuantity))throw errors.badRequest('PROMOTION_BOGO_INVALID','BOGO requires buy_quantity and get_quantity');
   const starts=request.body.starts_at!==undefined?request.body.starts_at:c.starts_at,ends=request.body.ends_at!==undefined?request.body.ends_at:c.ends_at;assertWindow(starts,ends);
   const timezone=request.body.schedule_timezone!==undefined?request.body.schedule_timezone:(c.schedule_timezone||await tenantTimezone(app.db,request.auth.tenantId));
   await app.db.query(`UPDATE promotions SET name=$1,status=$2,automatic=$3,value=$4,buy_quantity=$5,get_quantity=$6,min_subtotal=$7,max_discount=$8,first_order_only=$9,starts_at=$10,ends_at=$11,schedule_timezone=$12,usage_limit=$13,per_customer_limit=$14,metadata=$15::jsonb,updated_at=now() WHERE id=$16`,[request.body.name?.trim()??c.name,request.body.status??c.status,request.body.automatic??c.automatic,value,buyQuantity,getQuantity,request.body.min_subtotal??c.min_subtotal,request.body.max_discount!==undefined?request.body.max_discount:c.max_discount,request.body.first_order_only??c.first_order_only,starts,ends,timezone,request.body.usage_limit!==undefined?request.body.usage_limit:c.usage_limit,request.body.per_customer_limit!==undefined?request.body.per_customer_limit:c.per_customer_limit,JSON.stringify(request.body.metadata??c.metadata),c.id]);
   return {data:{promotion:await detail(app.db,request.auth.tenantId,store.id,request.params.promotionId)}};
 });
}
