import { errors } from '../../core/errors.js';
import { money } from '../orders/service.js';

function activeNow(row,now=new Date()){if(!['ACTIVE','SCHEDULED'].includes(row.status)) return false;if(row.starts_at&&new Date(row.starts_at)>now)return false;if(row.ends_at&&new Date(row.ends_at)<=now)return false;return true;}

async function eligibility(client,{tenantId,storeId,customerId,promotion,items,subtotal}){
  if(!activeNow(promotion)) return null;if(Number(subtotal)<Number(promotion.min_subtotal||0)) return null;
  if(promotion.first_order_only){const c=await client.query(`SELECT count(*)::int AS n FROM orders WHERE tenant_id=$1 AND customer_id=$2 AND status<>'CANCELLED'`,[tenantId,customerId]);if(c.rows[0].n>0)return null;}
  const usage=await client.query(`SELECT count(*)::int AS total,count(*) FILTER (WHERE customer_id=$4)::int AS customer_total FROM promotion_redemptions WHERE tenant_id=$1 AND store_id=$2 AND promotion_id=$3`,[tenantId,storeId,promotion.id,customerId]);
  if(promotion.usage_limit!=null&&usage.rows[0].total>=promotion.usage_limit)return null;if(promotion.per_customer_limit!=null&&usage.rows[0].customer_total>=promotion.per_customer_limit)return null;
  const targets=await client.query(`SELECT target_type,product_id,category_id FROM promotion_targets WHERE tenant_id=$1 AND store_id=$2 AND promotion_id=$3`,[tenantId,storeId,promotion.id]);
  let eligibleSubtotal=Number(subtotal);let eligibleItems=items;if(targets.rowCount){eligibleSubtotal=0;eligibleItems=[];for(const item of items){if(targets.rows.some(t=>t.target_type==='ORDER'||(t.target_type==='PRODUCT'&&t.product_id===item.product_id)||(t.target_type==='CATEGORY'&&t.category_id===item.category_id))){eligibleSubtotal+=Number(item.line_total);eligibleItems.push(item);}}}
  if(eligibleSubtotal<=0)return null;let discount=0;if(promotion.promotion_type==='PERCENTAGE')discount=eligibleSubtotal*(Number(promotion.value)/100);else if(promotion.promotion_type==='FIXED_AMOUNT')discount=Math.min(eligibleSubtotal,Number(promotion.value));else if(promotion.promotion_type==='BOGO'){const buy=Number(promotion.buy_quantity||0),get=Number(promotion.get_quantity||0);if(buy>0&&get>0){for(const item of eligibleItems){const qty=Number(item.quantity||0);const groups=Math.floor(qty/(buy+get));const freeQty=groups*get;const unit=qty>0?Number(item.line_total)/qty:0;discount+=freeQty*unit;}}}
  if(promotion.max_discount!=null)discount=Math.min(discount,Number(promotion.max_discount));return {promotion,eligibleSubtotal:money(eligibleSubtotal),discount:money(discount)};
}

export async function resolvePromotion(client,{tenantId,storeId,customerId,items,subtotal,promotionCode=null}){
  if(promotionCode){const found=await client.query(`SELECT p.*,pc.id AS promotion_code_id,pc.public_id AS promotion_code_public_id,pc.code,pc.usage_limit AS code_usage_limit FROM promotion_codes pc JOIN promotions p ON p.id=pc.promotion_id AND p.tenant_id=pc.tenant_id AND p.store_id=pc.store_id WHERE pc.tenant_id=$1 AND pc.store_id=$2 AND upper(pc.code)=upper($3) AND pc.status='ACTIVE' LIMIT 1 FOR UPDATE OF p,pc`,[tenantId,storeId,promotionCode.trim()]);if(!found.rowCount)throw errors.notFound('PROMOTION_CODE_INVALID','Promotion code is invalid or inactive');if(found.rows[0].code_usage_limit!=null){const used=await client.query(`SELECT count(*)::int AS n FROM promotion_redemptions WHERE tenant_id=$1 AND store_id=$2 AND promotion_code_id=$3`,[tenantId,storeId,found.rows[0].promotion_code_id]);if(used.rows[0].n>=found.rows[0].code_usage_limit)throw errors.conflict('PROMOTION_CODE_LIMIT_REACHED','Promotion code usage limit has been reached');}const result=await eligibility(client,{tenantId,storeId,customerId,promotion:found.rows[0],items,subtotal});if(!result)throw errors.conflict('PROMOTION_NOT_ELIGIBLE','Promotion is not eligible for this order');return {...result,promotionCodeId:found.rows[0].promotion_code_id,code:found.rows[0].code};}
  const autos=await client.query(`SELECT * FROM promotions WHERE tenant_id=$1 AND store_id=$2 AND status IN ('ACTIVE','SCHEDULED') AND automatic=true AND (starts_at IS NULL OR starts_at<=now()) AND (ends_at IS NULL OR ends_at>now()) ORDER BY created_at ASC FOR UPDATE`,[tenantId,storeId]);let best=null;for(const promo of autos.rows){const result=await eligibility(client,{tenantId,storeId,customerId,promotion:promo,items,subtotal});if(result&&(!best||result.discount>best.discount))best={...result,promotionCodeId:null,code:null};}return best;
}

export function applyPromotionToTotals({promotionResult,deliveryTotal}){if(!promotionResult)return {discountTotal:0,deliveryDiscount:0};if(promotionResult.promotion.promotion_type==='FREE_DELIVERY')return {discountTotal:0,deliveryDiscount:money(deliveryTotal)};return {discountTotal:promotionResult.discount,deliveryDiscount:0};}
