export const PERMISSIONS = Object.freeze({
  TENANT_SETTINGS_READ: 'tenant.settings.read',
  TENANT_SETTINGS_WRITE: 'tenant.settings.write',
  CUSTOMERS_READ: 'customers.read',
  CUSTOMERS_STATUS_MANAGE: 'customers.status.manage',
  CATALOG_READ: 'catalog.read',
  CATALOG_WRITE: 'catalog.write',
  INVENTORY_READ: 'inventory.read',
  INVENTORY_WRITE: 'inventory.write',
  ORDERS_READ: 'orders.read',
  ORDERS_MANAGE: 'orders.manage',
  PAYMENTS_READ: 'payments.read',
  PAYMENTS_MANAGE: 'payments.manage',
  DELIVERY_READ: 'delivery.read',
  DELIVERY_MANAGE: 'delivery.manage',
  PROMOTIONS_READ: 'promotions.read',
  PROMOTIONS_WRITE: 'promotions.write',
  CS_INTEGRATION_READ: 'integrations.customer_service.read',
  CS_INTEGRATION_MANAGE: 'integrations.customer_service.manage',
  MERCHANT_STAFF_READ: 'merchant.staff.read',
  MERCHANT_STAFF_MANAGE: 'merchant.staff.manage',
  MERCHANT_ROLES_READ: 'merchant.roles.read',
  MERCHANT_ROLES_MANAGE: 'merchant.roles.manage',
  MERCHANT_SESSIONS_MANAGE: 'merchant.sessions.manage',
  CUSTOMER_EXPERIENCE_READ: 'customer_experience.read',
  CUSTOMER_EXPERIENCE_MANAGE: 'customer_experience.manage',
  CUSTOMER_EXPERIENCE_PUBLISH: 'customer_experience.publish',
  AUDIT_READ: 'audit.read',
});

export const ALL_PERMISSIONS = Object.freeze(Object.values(PERMISSIONS));
